# This gist contains 10 randomly selected kmers (9mers) from the reference human genome (GRCh38).
The following code was used to generate the output:

import re, sys
from Bio import SeqIO
import random
import time

k = 9
n = 10
kmers = re.compile("(?=(\w{%s}))" % k)

def timer(start, end):
    hours, rem = divmod(end-start, 3600)
    minutes, seconds = divmod(rem, 60)
    return hours, minutes, seconds

start = time.time()

for rec in SeqIO.parse(sys.argv[1], 'fasta'):
    s = time.time()
    kseqs = kmers.findall(str(rec.seq))
    randomsel = random.sample(kseqs, n)
    e = time.time()
    h, m, s = timer(s, e)
    print("10 random kmers from {} [Elapsed time: {:0>2}:{:0>2}:{:05.2f}]\n{}".format(rec.id, int(h), int(m), s, str(randomsel)))

end = time.time()
hours, minutes, seconds = timer(start, end)
print("Total elapsed time: {:0>2}:{:0>2}:{:05.2f}".format(int(hours),int(minutes),seconds))

###### Start of output

10 random kmers from CM000663.2 [Elapsed time: 00:01:31.45]
['CCAGGAGAA', 'gttgcagtg', 'GCCATCAGT', 'tgcctccca', 'agaaaaatg', 'GCAGTGTTC', 'GCTGAGGTA', 'GCATGTCTG', 'ATTGATTCA', 'ACAAGTTTC']
10 random kmers from KI270706.1 [Elapsed time: 00:00:07.28]
['gaatagtaa', 'ataatttat', 'actttgttc', 'ttattacaa', 'TTAACATGT', 'TCAAAATTT', 'atggcctga', 'AGCCAAGGC', 'GCaagcagc', 'tccctacaa']
10 random kmers from KI270707.1 [Elapsed time: 00:00:00.02]
['AATGTGCAT', 'TACTCGTGG', 'ACTTAGTTG', 'TGCCAGTTG', 'tctggaGAA', 'aaagaaaaa', 'aaaagaagc', 'AGGTCCAGA', 'ttccagaac', 'Ccattcaca']
10 random kmers from KI270708.1 [Elapsed time: 00:00:00.05]
['tataataca', 'ATActttaa', 'AGGCAAGTC', 'CATAAAAGT', 'ttgtttctt', 'aggattggc', 'aaaaataac', 'GAATACCAG', 'AATCTTTtg', 'GTGTGAGTG']
10 random kmers from KI270709.1 [Elapsed time: 00:00:00.03]
['TGTCATGGG', 'ttccattcg', 'AATTTGCTC', 'ccaagactg', 'GTCTACTTG', 'ggacaccca', 'aatgtggcc', 'TAACATCAA', 'tgactattc', 'attcgatga']
10 random kmers from KI270710.1 [Elapsed time: 00:00:00.02]
['CAGCTAATG', 'GTCTGCTGC', 'GATTGTACA', 'tgttatact', 'ggaaaagca', 'tgcctccca', 'acaaactgt', 'CATGCATGT', 'CAAGAAAGT', 'TACATATAT']
10 random kmers from KI270711.1 [Elapsed time: 00:00:00.02]
['catgatggg', 'GACAAGTAT', 'CAGGTCAGT', 'GCCTTTGAG', 'TTAGTAACC', 'ATGCCATTT', 'ccatttctg', 'CAGCTTGCT', 'AGCACAGTC', 'tcctttttt']
10 random kmers from KI270712.1 [Elapsed time: 00:00:00.07]
['tggctggct', 'CCTCCATGT', 'gtgcagtgg', 'TGGCAGAGG', 'aaTATTTAC', 'aaaataaag', 'Ttacactgt', 'AAAGGAAAG', 'GAATGCTTT', 'aggaagaat']
10 random kmers from KI270713.1 [Elapsed time: 00:00:00.02]
['AAAATAATC', 'GGGGTGATG', 'acggagttt', 'GACTCTGGA', 'AGTGGTAAC', 'GGATGGATG', 'TTAAGGAGC', 'GAAAAGAGT', 'CTCTGTCTT', 'TCTTGGTTT']
10 random kmers from KI270714.1 [Elapsed time: 00:00:00.02]
['GTGTCCAGG', 'CTTTGATCa', 'AGCATTTTT', 'TGACCCATG', 'CAACCCATT', 'agacaaaga', 'ccccactgc', 'GAAAGATTT', 'TTGCATACA', 'GCTGCATCC']
10 random kmers from CM000664.2 [Elapsed time: 00:01:29.09]
['GCtcagagc', 'TAATCTAAA', 'TTCTACaaa', 'cttcccttc', 'TAAAAATTA', 'actaaaaag', 'NNNNNNNNN', 'AAAGCCACC', 'TCAAGTGGT', 'TCAAATCTT']
10 random kmers from KI270715.1 [Elapsed time: 00:00:07.04]
['atcttcccc', 'ctcaggact', 'tcgttggaa', 'cagagttga', 'tatttgtga', 'ttgaaacag', 'ttgaacagt', 'cgccctcaa', 'tctagacag', 'tgaaacacg']
10 random kmers from KI270716.1 [Elapsed time: 00:00:00.06]
['acagagttg', 'gtgcgccct', 'ttagaggat', 'tgaaacact', 'aacgggatt', 'aaaaaggaa', 'aaaaggaaa', 'attgtcttc', 'ggcctgcgg', 'ctttttgta']
10 random kmers from CM000665.2 [Elapsed time: 00:01:12.92]
['AGGCTGGAG', 'ttaacggac', 'AATTGCATT', 'TTTGGATAA', 'CACCATGCA', 'ctgaggtgg', 'gtgatcctc', 'aagaagttc', 'ATATTTTAT', 'GATTAGAAA']
10 random kmers from GL000221.1 [Elapsed time: 00:00:05.60]
['aaataaaaa', 'TTAGCTAAA', 'tagaactat', 'AGGCACtct', 'ctccagaca', 'tctgatatc', 'CTCCCCTAG', 'ATGTGCCTT', 'GTGTTTTAT', 'aaaaaaaaa']
10 random kmers from CM000666.2 [Elapsed time: 00:01:10.53]
['GTCTAAGAA', 'GAGTGGACC', 'gaaaaaaaa', 'aacggtaat', 'CAATCGAAA', 'gtcctcacc', 'ttcttttct', 'GCCAAATTC', 'GTAATTAAC', 'TGGGAGCAG']
10 random kmers from GL000008.2 [Elapsed time: 00:00:05.48]
['agtggagtc', 'GGAAACATT', 'atcctgtcg', 'tttctctaa', 'GAGGCTCTC', 'tagccatca', 'tGGTGTAAG', 'tcattagag', 'TGATACAAC', 'ttttcttgc']
10 random kmers from CM000667.2 [Elapsed time: 00:01:06.52]
['TGCATTTTA', 'ttggattta', 'ATCTTCAGT', 'ATTgctcaa', 'aaaaaaaaa', 'TTAACTGCG', 'aaattatta', 'TAACATGAC', 'CGCAAAAGT', 'tcaggattt']
10 random kmers from GL000208.1 [Elapsed time: 00:00:05.15]
['aggagctgt', 'ggtcaaaat', 'gtgtttcaa', 'atgttctac', 'tgtattggg', 'CACAAAggg', 'gagttgaat', 'AAAAGGATC', 'tagatcaaa', 'caaaagagt']
10 random kmers from CM000668.2 [Elapsed time: 00:01:02.70]
['CTGGGCCCT', 'catttcttg', 'GTGGTTGTG', 'TTCCACAGA', 'AGAGAGTTT', 'AGCActtca', 'TGGTCCCTG', 'TTGGTGAAC', 'CCAAAGGTG', 'ggcccctat']
10 random kmers from CM000669.2 [Elapsed time: 00:01:03.50]
['TTCTTCAAA', 'TTGCTCACT', 'cagcatcac', 'accgcaacc', 'TTTCTCTGA', 'attgctcag', 'acaggcatg', 'ACTTATATA', 'tcatttttt', 'ggttatttt']
10 random kmers from CM000670.2 [Elapsed time: 00:00:58.03]
['TGCAATGTT', 'ctccaatct', 'atccacctc', 'atatgtatt', 'TTAGatgtt', 'CAGCTGGGC', 'TACCACCAA', 'GCAAGTCTA', 'CTCCTGTAA', 'aagcaaata']
10 random kmers from CM000671.2 [Elapsed time: 00:00:55.14]
['GGAGTATGC', 'GAAATATCT', 'NNNNNNNNN', 'GTCTCTTAT', 'ccacaatgg', 'TTAGGGCCT', 'CTATATCCG', 'CATTCCCTA', 'TATTGATGA', 'CAGGTCTTT']
10 random kmers from KI270717.1 [Elapsed time: 00:00:03.97]
['TTAGGCTTC', 'AGAGAAGGT', 'aagtcctgA', 'ataaagggc', 'tttcaaaaa', 'agtccacaT', 'TACGTCTAG', 'aaaagccgc', 'TCCAATTGC', 'aaaggacat']
10 random kmers from KI270718.1 [Elapsed time: 00:00:00.01]
['CAAGGCTAT', 'taataattt', 'AAAGTGGAA', 'gcaacagac', 'tgcaatggt', 'aaggcaaaa', 'TCAACATAT', 'atttacata', 'gcatttatc', 'gcctcccga']
10 random kmers from KI270719.1 [Elapsed time: 00:00:00.06]
['GAGACCTCA', 'ATCTAGCCA', 'TAATCTCAC', 'TTGATTAAT', 'tacagccaa', 'AACGTAGTA', 'CTCTCATTC', 'gccagttta', 'atatgtata', 'caaataaaa']
10 random kmers from KI270720.1 [Elapsed time: 00:00:00.02]
['TGTGGAAGA', 'TTTCATCCT', 'GGTAGGAAA', 'tattctctg', 'aattgccac', 'tgtaAAGCA', 'CCCAgataa', 'atgggtgca', 'GGGAGCAGT', 'CATCTGAAA']
10 random kmers from CM000672.2 [Elapsed time: 00:00:49.05]
['agcacagta', 'ttgaatttt', 'GTATGAAtg', 'AGGTAGAAT', 'GTGGGACTT', 'NNNNNNNNN', 'CACATTCAT', 'AAAGCAGAT', 'ttctagaca', 'GTATATCTA']
10 random kmers from CM000673.2 [Elapsed time: 00:00:53.71]
['agctccagg', 'AGTTTTTTT', 'TTGTGACAT', 'AATGCGTAT', 'TGTAAGGGC', 'tctgtttct', 'agtggtgag', 'CAGATAGGA', 'CATTAGGGG', 'TGCTAGAAG']
10 random kmers from KI270721.1 [Elapsed time: 00:00:04.01]
['GGCAGGCAC', 'GAGGAACTG', 'TCCAGCAAC', 'AGTCCAGGC', 'GGTGTACGT', 'TCTGTGCCT', 'ccactgcac', 'GCTAAGGAA', 'TGGTCACCC', 'GATTTTTAA']
10 random kmers from CM000674.2 [Elapsed time: 00:00:48.71]
['aggaaaacg', 'gatttcttc', 'taataagta', 'ATCCTTACC', 'CTGTGTATG', 'gagttgaac', 'cacgtgcca', 'TTACTGGAC', 'CCACAAGTT', 'TGGGCAAGT']
10 random kmers from CM000675.2 [Elapsed time: 00:00:46.36]
['TGTGTGGAG', 'agaaggaaa', 'GCATCcagc', 'ACAACTCTG', 'ACATATATT', 'TATTTAATG', 'GTATTTTTG', 'TTCTGTAAC', 'CTAAAGTAG', 'ttataatta']
10 random kmers from CM000676.2 [Elapsed time: 00:00:42.39]
['AGTATTTTC', 'TGTTTCTTA', 'tgaaatttt', 'TTCTAAGAC', 'GATGAAAAC', 'NNNNNNNNN', 'TTAAAAGGC', 'NNNNNNNNN', 'GTTTGTATA', 'aaaagaaat']
10 random kmers from GL000009.2 [Elapsed time: 00:00:03.00]
['gcacctccc', 'GGtagtagc', 'TGTGAGCCC', 'TCCTGACCT', 'GACAAGTTC', 'ATCATGCAC', 'AACAAGTTA', 'TCCCAATAT', 'GAAATCAGG', 'tcttactca']
10 random kmers from GL000225.1 [Elapsed time: 00:00:00.08]
['AGTGGGAGC', 'taatggaat', 'gtgatgaaa', 'ACAGAAGAC', 'TAGCCTTTA', 'acataacTC', 'ttttttgta', 'ACACATCTC', 'gcagatctt', 'tcattattt']
10 random kmers from KI270722.1 [Elapsed time: 00:00:00.07]
['attatttag', 'TTGCATTAG', 'AATCCCACA', 'CATCCTTTC', 'AACTCACTT', 'atcctCCTG', 'TGCAAAGAG', 'tacaaaaca', 'ATgctacgt', 'gttgagtta']
10 random kmers from GL000194.1 [Elapsed time: 00:00:00.07]
['GGCTCCTAT', 'AGACAAGAC', 'gagagactc', 'CTGACTGGT', 'GGTGCGTCT', 'gatcacctg', 'GGGCTGGTG', 'gtacttgag', 'catggtgga', 'GAGAGGACG']
10 random kmers from KI270723.1 [Elapsed time: 00:00:00.02]
['GTAATGCTG', 'taaaaatta', 'agcctgaat', 'CACACCAAA', 'GTACCCGCC', 'ATCATCAAG', 'CCCGTATCT', 'GGGTGATGa', 'GCAGGGAAC', 'GAGCTATTC']
10 random kmers from KI270724.1 [Elapsed time: 00:00:00.01]
['CATGCCTAA', 'AGATTATGC', 'CATGTATAA', 'TTCCTTTTG', 'TGGGGCTAC', 'tgtaatata', 'tcatagcag', 'CATTACCTA', 'CCCAGTGCC', 'CCATattgt']
10 random kmers from KI270725.1 [Elapsed time: 00:00:00.06]
['tttggaggc', 'tgtggtggt', 'AAAAGAGTG', 'AGCTAGGAC', 'TAGAGATCA', 'GCCATTCCC', 'CTTTTCCTG', 'tgaattgaa', 'GATActgtt', 'ATTTGGACA']
10 random kmers from KI270726.1 [Elapsed time: 00:00:00.02]
['gtacagaaa', 'CCTATTGAC', 'CGGTTTGTC', 'acaggcaca', 'TGTGACTGG', 'TCACTCATG', 'CCCAGTATT', 'CTTCTGAGT', 'CTCTCAGGT', 'tatttctcc']
10 random kmers from CM000677.2 [Elapsed time: 00:00:37.40]
['TCATTGTGG', 'TTATCTTCT', 'ACACTGTGC', 'GTAAGCAAT', 'TGGATGGAG', 'TCCCCCGCT', 'TTTAATTTG', 'gccaccTAA', 'tattcacAG', 'NNNNNNNNN']
10 random kmers from KI270727.1 [Elapsed time: 00:00:02.84]
['TGATATTGC', 'CATGTTGCA', 'ggttgaact', 'agggacatg', 'tttattgaa', 'agttgaaat', 'GGCTTCTTA', 'CCTGTCTGG', 'ACATCTTGG', 'AACTGTTAA']
10 random kmers from CM000678.2 [Elapsed time: 00:00:33.21]
['taaggctag', 'aactcgaca', 'agaaaagga', 'ttgattcca', 'NNNNNNNNN', 'AGGGCTTCC', 'AATGTCTGT', 'NNNNNNNNN', 'ccctgtctg', 'ctactaaaa']
10 random kmers from KI270728.1 [Elapsed time: 00:00:03.08]
['ttcaactcc', 'tcaatattt', 'tgatcagag', 'CTTCCCAat', 'TGGCCGGTC', 'cacaccacc', 'TGTCAAAGC', 'cacttgaac', 'TTGGCACAG', 'ACTGAGGCA']
10 random kmers from CM000679.2 [Elapsed time: 00:00:30.49]
['agagctgaa', 'ATATATTGA', 'AGTCCAAAA', 'gggaggccg', 'aacggaatc', 'aggtgtggt', 'GTGAGATGG', 'CTCAAGTTT', 'TCCCCACTG', 'tcgcccagg']
10 random kmers from GL000205.2 [Elapsed time: 00:00:02.25]
['TGAAATCCT', 'TCTTAATTG', 'GGGAAAAGT', 'taaattatg', 'caggagtgt', 'aacattcag', 'AGGCTCCAG', 'ATTAGGAAT', 'TATTCGTAG', 'AGGTGTCCA']
10 random kmers from KI270729.1 [Elapsed time: 00:00:00.11]
['NNNNNNNNN', 'tccattcga', 'aatggaatg', 'gatgattat', 'cgatgattc', 'cgaatagaa', 'tatggaatg', 'tggaacgga', 'attccattg', 'TCTGTCCCC']
10 random kmers from KI270730.1 [Elapsed time: 00:00:00.04]
['NNNNNNNNN', 'gaatggatt', 'agtatgcac', 'taatatgga', 'ggaatggaa', 'gaaaggaat', 'tgtaatgga', 'NNNNNNNNN', 'TGAAGTgta', 'gctcgaatg']
10 random kmers from CM000680.2 [Elapsed time: 00:00:29.48]
['GCATCTTTT', 'CAACCAGTG', 'GAGCCCCTG', 'ttttgttgc', 'TGGGAAGAA', 'gagtgagac', 'ATTGCGGCA', 'gaacagaat', 'TGCACAAGT', 'GGGAGTGGG']
10 random kmers from CM000681.2 [Elapsed time: 00:00:23.89]
['GGGGACTTC', 'TGGGCTGGC', 'TTATAATTA', 'actaaaaat', 'aatgtcaga', 'ACTgttttg', 'GTGGCTGAG', 'acagtaata', 'tgatcatgc', 'CTATTATGA']
10 random kmers from CM000682.2 [Elapsed time: 00:00:25.32]
['GAGGACAAT', 'CCAACGTGT', 'ATGGAGGTG', 'TTCcaatta', 'TTTTCCTGA', 'TGGTTTATG', 'gctattatg', 'CGGCAGGGC', 'AAAATTCTC', 'attcaaggc']
10 random kmers from CM000683.2 [Elapsed time: 00:00:18.97]
['tgtagtata', 'aatgaaaat', 'AACCTGCCC', 'CTCGTTTGC', 'NNNNNNNNN', 'GTTCTGGTT', 'TTAATTGAC', 'catagaatt', 'TATATATAC', 'AGTTTTGAC']
10 random kmers from CM000684.2 [Elapsed time: 00:00:19.95]
['NNNNNNNNN', 'ttaggacag', 'NNNNNNNNN', 'CAGTGACCC', 'GAGGGATTC', 'TCATTGGAG', 'GGACTTCCG', 'ATCTCCCCC', 'CAGTAACTG', 'cagaagcat']
10 random kmers from KI270731.1 [Elapsed time: 00:00:01.34]
['TTCTTGAGT', 'aaataatgt', 'cagaaactg', 'tttgagatg', 'TGATTTCTC', 'cagatggtt', 'cccagcagt', 'GCAGCCCTG', 'aggcaccca', 'ATTTTAGGG']
10 random kmers from KI270732.1 [Elapsed time: 00:00:00.02]
['agggtaata', 'gcggcagcg', 'tgaaatgaa', 'catgtatat', 'AATAAATAA', 'GCCGCTTTT', 'tctctggga', 'ACtttttct', 'tggtaccat', 'AAAATAACC']
10 random kmers from KI270733.1 [Elapsed time: 00:00:00.06]
['GCCAGTTTG', 'tctcctgct', 'ctccctgtc', 'tcattattt', 'CGGTCGCTC', 'tatcatcaa', 'taactgaag', 'TACAGGAAA', 'ACCGCTTTT', 'tctcaggct']
10 random kmers from KI270734.1 [Elapsed time: 00:00:00.06]
['ACCATAGCT', 'ACCTTGCAA', 'TCTTACCAT', 'TATCTTCAA', 'CTAGGGGGT', 'GCTAGTAGT', 'CACAAACAG', 'caagatatt', 'GATAGGTGG', 'GGGTGGGGA']
10 random kmers from KI270735.1 [Elapsed time: 00:00:00.02]
['Ctccaaagg', 'tgagatctt', 'attcgattc', 'GAATGCAAA', 'tcatttttt', 'caaaagaac', 'gtcaaaaag', 'GATTAATCT', 'ttgtgtcac', 'CCTCATGAA']
10 random kmers from KI270736.1 [Elapsed time: 00:00:00.06]
['tggattgga', 'tgcagtaga', 'gaaattcaa', 'GGTGCAATG', 'GAAACCATG', 'gtggagtag', 'atgtggaag', 'ggaatggag', 'CCCAATCCT', 'tggaatgga']
10 random kmers from KI270737.1 [Elapsed time: 00:00:00.04]
['tccttttga', 'GGGCcgagc', 'ttccagacA', 'atttgattc', 'ccattgcat', 'tccattcca', 'ttcaattcc', 'ccattcgag', 'ccgtgtcca', 'cctttccat']
10 random kmers from KI270738.1 [Elapsed time: 00:00:00.03]
['catcgtatg', 'gaatggact', 'CCGAAATGA', 'Gtcaatttt', 'caaagaagg', 'AAgggaaac', 'gaagggaat', 'ttggaatca', 'atggaatga', 'ctgagaaaa']
10 random kmers from KI270739.1 [Elapsed time: 00:00:00.03]
['atggaaaaa', 'attctgaga', 'tgatgtttg', 'ggaagtgga', 'ttgaatgca', 'ttgaggcct', 'gacatttga', 'gccCAGTTT', 'tcctcaaag', 'cagacactt']
10 random kmers from CM000685.2 [Elapsed time: 00:00:57.07]
['CTCAGCTCA', 'TCAGTGTCA', 'TGCTGTCCT', 'TGACTGAGG', 'TGCTGCTTC', 'tctcagaat', 'caagtggac', 'GGACTGTTA', 'atatttgtg', 'GAAGTGGGT']
10 random kmers from CM000686.2 [Elapsed time: 00:00:25.54]
['tgtcttctg', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'CAAATTTGA', 'NNNNNNNNN', 'TAATTACTT', 'NNNNNNNNN']
10 random kmers from KI270740.1 [Elapsed time: 00:00:01.60]
['tgaagctgc', 'ttgtCCTTC', 'TATGTCCAG', 'agaatgaag', 'gaGGTGTTa', 'gtgcagagt', 'actgttaca', 'agaccttag', 'tgtgtccag', 'cctttacgg']
10 random kmers from KI270302.1 [Elapsed time: 00:00:00.00]
['gtggaactc', 'aacattctt', 'aaacgggta', 'cctgcaagc', 'cattcttat', 'gaggatttc', 'CTTCTTTGT', 'cttgtgagt', 'tgaaacact', 'aaagtaaac']
10 random kmers from KI270304.1 [Elapsed time: 00:00:00.00]
['aggtctgaa', 'ctagttttt', 'aaattccat', 'atgaaaaaa', 'agttgaatg', 'agagtgttt', 'gtgcagact', 'ttcttctgt', 'cttgcaaat', 'ctaaatgaa']
10 random kmers from KI270303.1 [Elapsed time: 00:00:00.00]
['cgcagtttg', 'aagaaatcc', 'tctactatt', 'tgcaaattc', 'actctggga', 'ggaagtttc', 'ttcctaact', 'tcaactctg', 'tatccactt', 'tttctgaga']
10 random kmers from KI270305.1 [Elapsed time: 00:00:00.00]
['gtgaagaag', 'gatacagca', 'tactttcct', 'aactatatt', 'TTtgttgcg', 'gatgtttgc', 'tggaaacac', 'ggaaacact', 'gatggaaaa', 'TGaagactg']
10 random kmers from KI270322.1 [Elapsed time: 00:00:00.01]
['NNNNNNNNN', 'NNNNNNNNN', 'ccgtgagat', 'cctatccat', 'gagtgtttc', 'NNNNNNNNN', 'gtttcaaac', 'NNNNNNNNN', 'NNNNNNNNN', 'cacgaagct']
10 random kmers from KI270320.1 [Elapsed time: 00:00:00.00]
['agagctgaa', 'ttcgaggcc', 'gatgattcc', 'ggaaatagc', 'aagtcacag', 'cataaaaac', 'cagagttga', 'tttggatat', 'aaaagatag', 'acggagtgg']
10 random kmers from KI270310.1 [Elapsed time: 00:00:00.00]
['cacaacaca', 'caaggaagt', 'cctaactgc', 'gagttgaat', 'gtgagttga', 'cattctgtc', 'agcggctga', 'ttcaactct', 'ctgtctagt', 'tccaacgaa']
10 random kmers from KI270316.1 [Elapsed time: 00:00:00.00]
['acagaagaa', 'cagagcaga', 'aaacgggtt', 'tgtgttgtg', 'agacagaat', 'ctgtaaagt', 'tgagacctc', 'tggtataaa', 'agagtttaa', 'agatttgaa']
10 random kmers from KI270315.1 [Elapsed time: 00:00:00.00]
['gatttgaaa', 'ccgtgtgtt', 'gcgttcaac', 'acagagcag', 'ggccttcgt', 'gccctcgtt', 'aagtggata', 'tgcattcaa', 'acgatcctt', 'ttcaaaact']
10 random kmers from KI270312.1 [Elapsed time: 00:00:00.00]
['accacaaaa', 'tcgttcaac', 'acaaacaga', 'gaaagttaa', 'atcaaagcg', 'ttctgagaa', 'tacacacaa', 'aagtctgct', 'ctccacttg', 'ctgagaatt']
10 random kmers from KI270311.1 [Elapsed time: 00:00:00.00]
['NNNNNNNNN', 'ttttcatag', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'cagtaactt', 'NNNNNNNNN', 'ttgtgtgta']
10 random kmers from KI270317.1 [Elapsed time: 00:00:00.01]
['NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'gaccttaaa', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN']
10 random kmers from KI270412.1 [Elapsed time: 00:00:00.00]
['tttacagac', 'agaaagaag', 'gtctagcag', 'agaattctt', 'cacacatca', 'cgaatgact', 'agaatgatt', 'aactgccct', 'agttgaatt', 'ggatCCAAA']
10 random kmers from KI270411.1 [Elapsed time: 00:00:00.00]
['tttactgag', 'actctgtgt', 'ccatctCTA', 'gtctaaaaa', 'tgaatacac', 'aaatctcca', 'tgtctaaga', 'aagagggcc', 'actctgtga', 'ttctgagaa']
10 random kmers from KI270414.1 [Elapsed time: 00:00:00.00]
['cagaatcat', 'tgaggccaa', 'cttctaggc', 'tttcttttc', 'ttgtgtgta', 'atctctttc', 'ctcacagat', 'gcattcaac', 'tattcaaca', 'ttgaacctt']
10 random kmers from KI270419.1 [Elapsed time: 00:00:00.00]
['agcagctat', 'aaacagaag', 'gatgattgg', 'ccaaTGGAG', 'atctgcaag', 'GTCActgtt', 'atcaaacct', 'gtgaagact', 'GATTCGGac', 'gaaactctc']
10 random kmers from KI270418.1 [Elapsed time: 00:00:00.00]
['taggttctc', 'gtttacaac', 'aaaggagtt', 'ggtttcaga', 'gctgttctg', 'ctgcaagtt', 'cacagattc', 'ctctatcta', 'agaaaaagg', 'gggaaattt']
10 random kmers from KI270420.1 [Elapsed time: 00:00:00.00]
['tgcagattc', 'gaaaaagag', 'caatgcttc', 'gagaatgct', 'gaaaggaaa', 'cttcaaaga', 'tagttttta', 'ttccaacga', 'caaagaggt', 'aaagtagtt']
10 random kmers from KI270424.1 [Elapsed time: 00:00:00.00]
['tcttcacat', 'acagagctg', 'agaaacatc', 'ctttgatag', 'ctgtttttg', 'tgattgcat', 'acattggca', 'tggagcagt', 'cattctcag', 'GTTCCAAAC']
10 random kmers from KI270417.1 [Elapsed time: 00:00:00.00]
['cttctcata', 'gcagaaact', 'aggcctatg', 'AACAttcct', 'gaaatatct', 'aatctgcaa', 'tggtgaaaa', 'aaaggaaat', 'gaccacttt', 'CAACTagta']
10 random kmers from KI270422.1 [Elapsed time: 00:00:00.00]
['aaagaggtc', 'tggagtcat', 'aactctgtg', 'gattctaca', 'aggaaacat', 'tttactaca', 'gttcaactc', 'tgcagattc', 'acttgcaga', 'tttttagat']
10 random kmers from KI270423.1 [Elapsed time: 00:00:00.00]
['ctttctgta', 'aacgggtat', 'ttggaaatg', 'tcaaacact', 'gaaacaggt', 'ttctttgga', 'ttctcagaa', 'tgagcaatc', 'gttgaacct', 'agttcagct']
10 random kmers from KI270425.1 [Elapsed time: 00:00:00.00]
['ttcaactca', 'tttgtagaa', 'aaatatctt', 'ctttgaggc', 'gattgtaTT', 'gaaactctc', 'gacttcttt', 'ctgatgatt', 'AActgagag', 'gtgtttagt']
10 random kmers from KI270429.1 [Elapsed time: 00:00:00.00]
['tttcataga', 'aactcacag', 'ccttctttg', 'tatgtgttg', 'gtaccttat', 'tttgtacaa', 'atactctgt', 'aactcacag', 'gtagaaaag', 'tgagccctt']
10 random kmers from KI270442.1 [Elapsed time: 00:00:00.14]
['tttaatctc', 'gaaaggttc', 'tcaaatgga', 'tttcagatt', 'cagaagcca', 'tgagaaact', 'NNNNNNNNN', 'tcaaaagaa', 'caaacctgc', 'GCCtgaagt']
10 random kmers from KI270466.1 [Elapsed time: 00:00:00.01]
['agtttaTTA', 'tatttgatg', 'ttttggata', 'TATTTGATA', 'GTAATTTGA', 'cagtatata', 'agtatataa', 'atactttgt', 'TACagtgta', 'tattttatg']
10 random kmers from KI270465.1 [Elapsed time: 00:00:00.00]
['tccaaactg', 'ggtacacac', 'aaagcgttc', 'tctaaactg', 'cattagagc', 'cgtttccaa', 'atgatgata', 'attcttcat', 'cttctgtct', 'cctttcgct']
10 random kmers from KI270467.1 [Elapsed time: 00:00:00.00]
['tatataata', 'catatttta', 'actttcata', 'ttatgtaca', 'aatatatat', 'tttgatatt', 'tTTGGGTAC', 'tgagcacgt', 'atataatac', 'ATGCACAGT']
10 random kmers from KI270435.1 [Elapsed time: 00:00:00.03]
['atggtgtaa', 'cttttagtA', 'cataaaaac', 'cgaaaagac', 'cacagaagc', 'tgtttttgt', 'ttctgacaa', 'aatagctta', 'AAATAAtcc', 'gtatcagaA']
10 random kmers from KI270438.1 [Elapsed time: 00:00:00.04]
['aaaattctt', 'gaatggaat', 'atggacaGG', 'ttttgagaa', 'AATGGAACT', 'tggattgta', 'NNNNNNNNN', 'gaaatatct', 'ggagctgat', 'ggaatagaa']
10 random kmers from KI270468.1 [Elapsed time: 00:00:00.00]
['ggtttgaaa', 'ttgaaacac', 'agacagaag', 'aataTGTTT', 'attgaacat', 'aaacttctt', 'ggacatttg', 'tggatagcc', 'cagttttga', 'agtggataa']
10 random kmers from KI270510.1 [Elapsed time: 00:00:00.00]
['tgtgggaaa', 'atttagcag', 'tgtgtgcat', 'ttggacatt', 'atatttcga', 'ttttgattg', 'cttcacata', 'ttcacagaa', 'aaacttttt', 'agcccttgt']
10 random kmers from KI270509.1 [Elapsed time: 00:00:00.00]
['agatattta', 'tccacttgc', 'acaaagtat', 'tcaatcaaa', 'tgaagacac', 'caaagaagt', 'Cttctctgg', 'ttccttttc', 'taaaatctg', 'tttatgtga']
10 random kmers from KI270518.1 [Elapsed time: 00:00:00.00]
['atttggagc', 'aaaggaaat', 'actctttca', 'aaaaactag', 'gaaatatct', 'gaagcattc', 'gaaaactac', 'tttttgtga', 'atttgaggc', 'tgaacctgt']
10 random kmers from KI270508.1 [Elapsed time: 00:00:00.00]
['aatttgatc', 'cactttcag', 'tgattttgc', 'cccatattt', 'tgTTCTGTC', 'ttcctgggt', 'aattcctgg', 'tgtctctgc', 'atgaagttt', 'ctgcccctg']
10 random kmers from KI270516.1 [Elapsed time: 00:00:00.00]
['ggaacctgt', 'aatctgaaa', 'aatacacgg', 'agtggatat', 'tctgcaggt', 'aatatcttc', 'caactcaca', 'gcattctga', 'cataaaaac', 'ggtggaaaa']
10 random kmers from KI270512.1 [Elapsed time: 00:00:00.01]
['tttctcaga', 'ttaggattg', 'acggagtcc', 'gtgctccaa', 'atggagtgg', 'gggttttct', 'tctcagaat', 'ttctcaaaa', 'aagatattt', 'ctgctggat']
10 random kmers from KI270519.1 [Elapsed time: 00:00:00.05]
['aattAGACA', 'agaatctgc', 'atcaggtca', 'caatgccat', 'atctgaaga', 'ttggaacca', 'tgcacattt', 'ctacagaga', 'tttaactct', 'tcaactctc']
10 random kmers from KI270522.1 [Elapsed time: 00:00:00.00]
['cctcaaaca', 'taggcctga', 'GGGAATGTG', 'ccaaatatc', 'tctgtctag', 'caaaactgc', 'ttatatgaa', 'aactgttct', 'aggcatcaa', 'tttccaatt']
10 random kmers from KI270511.1 [Elapsed time: 00:00:00.00]
['ccccaaata', 'tcaccaaga', 'tccacttgc', 'gaagtttca', 'tctgagaat', 'aaaaagaga', 'accTCTCTG', 'gggctccaa', 'aagaggttt', 'atccacttg']
10 random kmers from KI270515.1 [Elapsed time: 00:00:00.00]
['tttgaatct', 'tcctttatt', 'tatttggag', 'aaatctaga', 'tcacagagt', 'ttttgtttg', 'aaacactct', 'ttcctttga', 'agtttcaaa', 'tgtgcattc']
10 random kmers from KI270507.1 [Elapsed time: 00:00:00.00]
['tgtgatgtg', 'aaacttctt', 'AGGAagcat', 'tcacataaa', 'tttgtgatg', 'aattctgag', 'ctggaagtg', 'tgtgtgcat', 'aaacctttc', 'gaggagttt']
10 random kmers from KI270517.1 [Elapsed time: 00:00:00.00]
['aaaagagag', 'gaatgctac', 'tcgtcagaa', 'cgaaaagag', 'aagagagat', 'gatattgcc', 'gaatgcaca', 'gagtttcaa', 'aagcactcc', 'tgtgaagat']
10 random kmers from KI270529.1 [Elapsed time: 00:00:00.00]
['aggttcaac', 'tgaatggga', 'acacttgca', 'tgtttcaaa', 'tgcttcttc', 'aacctgttc', 'acttgaatg', 'aaTTCCAAT', 'aaggtccac', 'ttacaaaaa']
10 random kmers from KI270528.1 [Elapsed time: 00:00:00.00]
['ccattcgag', 'tcgttttga', 'GTGCATTTG', 'attcgatga', 'tccattctt', 'aattccatt', 'ccattctat', 'ccatttgat', 'tgatgattc', 'CGttgattc']
10 random kmers from KI270530.1 [Elapsed time: 00:00:00.00]
['aaactcctt', 'agagttgaa', 'gatttcagc', 'gaggacttc', 'attcaactg', 'atgtgtatt', 'gagcagatt', 'aaatatctt', 'ttcaactca', 'atggtagaa']
10 random kmers from KI270539.1 [Elapsed time: 00:00:00.00]
['tccgggggg', 'cggccagcc', 'ccagccacc', 'cgggaggga', 'ggggtcaga', 'gtccgggag', 'gccccccgc', 'CCcgctgcc', 'cccgcccgg', 'tccgggagg']
10 random kmers from KI270538.1 [Elapsed time: 00:00:00.03]
['NNNNNNNNN', 'ctcaaaagg', 'NNNNNNNNN', 'tatccaaaa', 'tttttgtag', 'NNNNNNNNN', 'gttcaactc', 'aaagtgTCT', 'ctctttggA', 'NNNNNNNNN']
10 random kmers from KI270544.1 [Elapsed time: 00:00:00.00]
['aggaagttt', 'tttctgaga', 'tccacaaaa', 'tttttatgg', 'atgttcaac', 'gctgagtag', 'gggaatgtt', 'atgcaacca', 'cctgaaagc', 'tccaacgaa']
10 random kmers from KI270548.1 [Elapsed time: 00:00:00.00]
['actctttct', 'aagcattct', 'ttggatagc', 'gtagtatct', 'gcattctca', 'gtttgcttt', 'gacagtagc', 'tggagcgct', 'atgtatgtc', 'tttcgtcgg']
10 random kmers from KI270583.1 [Elapsed time: 00:00:00.00]
['aaggagaac', 'cccatctca', 'CTcgtttaa', 'ctgcacatt', 'ataaagcaa', 'ggataccca', 'catctgaat', 'tcctttgta', 'atagacatc', 'aatttttta']
10 random kmers from KI270587.1 [Elapsed time: 00:00:00.00]
['gtaggccac', 'cagtcaaaa', 'cacttgcag', 'caatcaaaa', 'gtaggcctc', 'ttaaaaaat', 'caaaaaggg', 'tccaaagaa', 'actgcacac', 'tgcttctgc']
10 random kmers from KI270580.1 [Elapsed time: 00:00:00.00]
['gctctttta', 'ATTTaccaa', 'gttgttgaa', 'tttaagaat', 'ttcaacttc', 'ctattgatt', 'ttaagaatg', 'ttgaatagg', 'tgtagttct', 'tcttattat']
10 random kmers from KI270581.1 [Elapsed time: 00:00:00.00]
['ACTTCACAA', 'CATTTCTCT', 'aactggaaa', 'ATCAGAAAG', 'tctgatctt', 'cattgcctc', 'aaaaaaaaa', 'cttctgcat', 'atttccagc', 'ttgcagctt']
10 random kmers from KI270579.1 [Elapsed time: 00:00:00.01]
['gtagttttt', 'cagaatgct', 'caactctgt', 'caaaaagag', 'ctgtgagat', 'cataagata', 'tcaacaatg', 'acacaatac', 'atgtaccct', 'tcacaaaga']
10 random kmers from KI270589.1 [Elapsed time: 00:00:00.01]
['agaaatttc', 'atctcacag', 'NNNNNNNNN', 'gtttaccca', 'ttctgtcta', 'ttttccacc', 'cagtatttt', 'gtttccaaa', 'catcaaaag', 'tacacatca']
10 random kmers from KI270590.1 [Elapsed time: 00:00:00.00]
['taggcctca', 'cctcaaagt', 'actgctata', 'acacatctc', 'aaacatcac', 'caaagaatt', 'Ctacaaata', 'aactgctgt', 'gttaatata', 'tgagttgaa']
10 random kmers from KI270584.1 [Elapsed time: 00:00:00.00]
['tgaatcaaa', 'tatgtgaag', 'tttaaaaac', 'agaagtttg', 'tcaaaactg', 'tttctcaga', 'tattccctt', 'ttatgtgaa', 'agtctttca', 'gtgaagata']
10 random kmers from KI270582.1 [Elapsed time: 00:00:00.00]
['atgcatgtg', 'ctgcacccc', 'cctactgtc', 'ttaaggact', 'gcatttcat', 'ctcactgca', 'tgtatttct', 'agtcttgct', 'agtttaact', 'ttgaatggt']
10 random kmers from KI270588.1 [Elapsed time: 00:00:00.00]
['tagtcttta', 'aagtttctc', 'tgtgaggat', 'ctctctttt', 'tgtaaacac', 'cttgcagat', 'agataggtt', 'ggaaaggaa', 'actctcttt', 'attgtcttt']
10 random kmers from KI270593.1 [Elapsed time: 00:00:00.00]
['caatctggg', 'tgtagaatc', 'gtccattca', 'ttttgattg', 'actcctttt', 'gacatttgg', 'gaGAGAAGc', 'agacagaag', 'acagaagca', 'gcgccttgt']
10 random kmers from KI270591.1 [Elapsed time: 00:00:00.00]
['gccccaagg', 'tgctgcact', 'aaacttctc', 'attctacaa', 'gccttgatt', 'ccaattgca', 'ttccatcag', 'catttgcag', 'aaagaagtt', 'ttctctatc']
10 random kmers from KI270330.1 [Elapsed time: 00:00:00.00]
['TACACCTGT', 'GTAGACATT', 'CAGTGACAC', 'CACGCATCC', 'tttctctct', 'TCCGTTGTA', 'GTCAGGAAT', 'GCCTTAGGT', 'ttccttcct', 'catccttct']
10 random kmers from KI270329.1 [Elapsed time: 00:00:00.00]
['agagtattt', 'attctgcaa', 'ggcctcaaa', 'aagagtgtt', 'cacctctgt', 'caatacttc', 'ttgcaaatt', 'ctttttctg', 'tttcaaaac', 'gaatgcaaa']
10 random kmers from KI270334.1 [Elapsed time: 00:00:00.00]
['gtagaatct', 'tgtgaactc', 'actcacaga', 'cgcttagag', 'CTGcttgag', 'gcagttttg', 'tttgtagaa', 'ctctttcag', 'tcacagagt', 'GACAGAAAC']
10 random kmers from KI270333.1 [Elapsed time: 00:00:00.00]
['aaaatatca', 'actgtacat', 'tgtatactg', 'ATACtgcac', 'aaatatcaa', 'GTATGTAtt', 'TCTACATAA', 'tttataata', 'tgtattgta', 'ctgtacata']
10 random kmers from KI270335.1 [Elapsed time: 00:00:00.00]
['tcgttgtaa', 'actcaaaga', 'ttgtaaacg', 'cattcaact', 'actcacaga', 'gatgtctgc', 'CTCTGAAAC', 'ggggtATCT', 'agatcagtt', 'cattctcag']
10 random kmers from KI270338.1 [Elapsed time: 00:00:00.00]
['tctcagaaa', 'ATttgtagg', 'tttgtgatg', 'TCcgcacat', 'TGTTTTTGC', 'aatctgctt', 'agctcttgg', 'agatcagtt', 'catactctg', 'tgtgttgtg']
10 random kmers from KI270340.1 [Elapsed time: 00:00:00.00]
['aacatttag', 'ttgtgatgt', 'atttgaggc', 'gatagagct', 'TGCAAGTGt', 'acagttctt', 'ttcatttgg', 'cattctcag', 'aaaaactaa', 'tgcagtatc']
10 random kmers from KI270336.1 [Elapsed time: 00:00:00.00]
['caaagtatg', 'TACTATATA', 'ataaaatat', 'atactgtac', 'atcaaagta', 'gtacataaa', 'TATTATaca', 'tactgtaca', 'cattatata', 'taaaatatc']
10 random kmers from KI270337.1 [Elapsed time: 00:00:00.00]
['ttatatact', 'attatatac', 'tattatata', 'aaatatcaa', 'tattatatc', 'aagtaccca', 'aaatatgta', 'aagtaccca', 'tacccaaag', 'CCTTTATAG']
10 random kmers from KI270363.1 [Elapsed time: 00:00:00.00]
['gcctttttt', 'gtgattttg', 'tagagtttc', 'agatagttt', 'gctagcagt', 'ttcctgggt', 'atccactgt', 'catttcaac', 'gcatcccag', 'gtaacccga']
10 random kmers from KI270364.1 [Elapsed time: 00:00:00.00]
['atcagaatg', 'tctcagaat', 'aaagaatgt', 'aaggcgctc', 'gtgtaattt', 'agtgtttcc', 'acttgcaga', 'gtgtagttt', 'ccacGAAGG', 'actgctgaa']
10 random kmers from KI270362.1 [Elapsed time: 00:00:00.00]
['agaaggttc', 'gtctagttt', 'aaagagtgt', 'tgtttcaaa', 'tgtgaagat', 'gagaatgct', 'TCGatatgt', 'acatcacaa', 'attatccac', 'catcaaaaa']
10 random kmers from KI270366.1 [Elapsed time: 00:00:00.00]
['aaaagagtg', 'ctaactgct', 'tcaaaagga', 'atgcacaca', 'cgtaagcct', 'gcacacatc', 'acattcaac', 'cctcaaagt', 'tttctgaaa', 'aagagtttt']
10 random kmers from KI270378.1 [Elapsed time: 00:00:00.00]
['tctttttga', 'tacatataa', 'atggctttg', 'caagtggat', 'gcaggttgg', 'aaacttatt', 'tgtgtgtcc', 'gattctgca', 'aatttcgtt', 'gcaagtgga']
10 random kmers from KI270379.1 [Elapsed time: 00:00:00.00]
['ggacctctt', 'aaacctagg', 'ctataaaaa', 'caatgggga', 'aaagctgga', 'cttaaatgt', 'aactggaaa', 'ggattccct', 'ctactttaa', 'tacaggaaa']
10 random kmers from KI270389.1 [Elapsed time: 00:00:00.00]
['tgtgtgtat', 'gaaacactc', 'ttttggaaa', 'aacactctt', 'caagtaaca', 'gcctatgtt', 'tgctgtatg', 'agttgatac', 'tgtagtatc', 'catttggag']
10 random kmers from KI270390.1 [Elapsed time: 00:00:00.00]
['aacttattt', 'gttttgata', 'ttgaaacac', 'ttggaaacg', 'atatttgga', 'aaaggaaat', 'cagagatga', 'acttctttg', 'agcaggttt', 'tgttctcaa']
10 random kmers from KI270387.1 [Elapsed time: 00:00:00.00]
['tggatacaa', 'ttgcattca', 'actagacag', 'actttcagg', 'tcaagcact', 'gtgtgtatt', 'atatcttct', 'aaatatctt', 'cattctcag', 'gaacttctt']
10 random kmers from KI270395.1 [Elapsed time: 00:00:00.00]
['tgcttcaaa', 'ggttcaact', 'aactctgtt', 'aaaggttca', 'ctgtgagtt', 'tgaatgcaa', 'cacagagaa', 'agaaagatt', 'cttgatttc', 'gaagtttct']
10 random kmers from KI270396.1 [Elapsed time: 00:00:00.00]
['tgtccaacg', 'ctgttaatt', 'tgaaagcgc', 'gaatgcttc', 'ttcaactct', 'agaaaggtt', 'acccaaaca', 'tctccctag', 'tgttgtacc', 'tctggtttt']
10 random kmers from KI270388.1 [Elapsed time: 00:00:00.00]
['ctctttttg', 'ttgaggatt', 'gttggaaac', 'atataaaat', 'tctctgtga', 'ctaacagag', 'gttgaaaaa', 'ctcatagag', 'cagaaactt', 'acgttcctt']
10 random kmers from KI270394.1 [Elapsed time: 00:00:00.00]
['aacacttcc', 'aaaatctag', 'acattggca', 'tagatagga', 'tttcataga', 'aagatttcc', 'ataaaatct', 'aactaacag', 'atataaaat', 'ttctttgga']
10 random kmers from KI270386.1 [Elapsed time: 00:00:00.00]
['aagaaggtt', 'tatctcctt', 'tcacaaaga', 'atgtaatcc', 'ttcggattc', 'cagaaagag', 'tctgagaat', 'ggttcaact', 'tgttcaact', 'tattcaact']
10 random kmers from KI270391.1 [Elapsed time: 00:00:00.00]
['gtgtacaga', 'tgtatgaag', 'tcttgattt', 'ccgagaagt', 'gttgaggac', 'agagggttt', 'taaaaagaa', 'agtttcaaa', 'aagctatcc', 'gggaagtgt']
10 random kmers from KI270383.1 [Elapsed time: 00:00:00.00]
['tccaaatgt', 'gttttatat', 'tgtatcaaa', 'tttatatga', 'aaaaagagt', 'cgcttgaaa', 'taaaaggga', 'aagttcctg', 'catcacaaa', 'aacgtcagc']
10 random kmers from KI270393.1 [Elapsed time: 00:00:00.00]
['gggaatgtt', 'ggtatcaaa', 'agcgctgcc', 'caggtagtg', 'tccattcca', 'gtttcaaac', 'caaacatca', 'ttgagtaca', 'ctatctaaa', 'ataaaaggg']
10 random kmers from KI270384.1 [Elapsed time: 00:00:00.00]
['cagattcta', 'acaaaaaga', 'aaacggctc', 'tccaaatat', 'acaaaggtt', 'atgagttga', 'aagctatcc', 'gcaagcatc', 'acaaaggtt', 'ttccttttt']
10 random kmers from KI270392.1 [Elapsed time: 00:00:00.00]
['tccttggaa', 'tcgatacag', 'ccatacaga', 'tttgaagtt', 'agcattctc', 'gtggatatt', 'tgcattgaa', 'ctttcatag', 'ctctttctg', 'ctcaactaa']
10 random kmers from KI270381.1 [Elapsed time: 00:00:00.00]
['aacgtgctc', 'ccacgtagt', 'tatcaaaac', 'cctacaaaa', 'tcccgtttc', 'caaatatcc', 'aaacatgct', 'gaaatgtcc', 'aagatattc', 'caaaacaaa']
10 random kmers from KI270385.1 [Elapsed time: 00:00:00.00]
['gcattctca', 'ctgatacaa', 'aacgggaat', 'tccttggaa', 'caactcata', 'cattttgga', 'catagagca', 'gtatctgaa', 'caattagca', 'attctcaga']
10 random kmers from KI270382.1 [Elapsed time: 00:00:00.00]
['ttttttttg', 'atacagcac', 'tagaatctg', 'agatagcta', 'gtaatattt', 'ggtgaaaat', 'tttggaaac', 'aaacttgtt', 'ctttctgta', 'tcaactaac']
10 random kmers from KI270376.1 [Elapsed time: 00:00:00.00]
['tttaacttt', 'gcagagtct', 'tatttGAGA', 'aaggttcaa', 'tgtccactt', 'aggttcaac', 'aagaaaggt', 'aagtggttt', 'acaaagtgg', 'ctctgtggg']
10 random kmers from KI270374.1 [Elapsed time: 00:00:00.00]
['gcaagtgga', 'acactcttt', 'ttcacataa', 'gagctttga', 'aaatatctt', 'ttgagccct', 'agtttggaa', 'agagctttg', 'tgattgagc', 'tttgtgatg']
10 random kmers from KI270372.1 [Elapsed time: 00:00:00.00]
['agggctcaa', 'aagtatctc', 'aaagtgctc', 'attctacaa', 'gtttctcag', 'ctaaaactt', 'tgctcaatc', 'gcacatatc', 'gaagtagtt', 'acgctgtga']
10 random kmers from KI270373.1 [Elapsed time: 00:00:00.00]
['tgagcgtgg', 'actagaaag', 'aatggggag', 'GAAGCCTTC', 'tttgaaaca', 'gaactttac', 'tgtcaaaga', 'ggttccata', 'tctctgttt', 'atgtgtgca']
10 random kmers from KI270375.1 [Elapsed time: 00:00:00.00]
['gagttgaat', 'aacgaagtt', 'agggctcca', 'gtttcaaaa', 'ataggttca', 'cctcaaagt', 'gataggttc', 'aatatccac', 'gaagaaatt', 'atccacttg']
10 random kmers from KI270371.1 [Elapsed time: 00:00:00.00]
['gattgagca', 'aaagcaaat', 'gaaaagtaa', 'tttagagct', 'gcagaatct', 'tttagaatc', 'agaaacttc', 'tgaggaact', 'ctgtctttt', 'tttgtagat']
10 random kmers from KI270448.1 [Elapsed time: 00:00:00.00]
['acgggtata', 'tagagcagt', 'gacagaaac', 'atatctgga', 'AAAGCAAAC', 'TGCCTATGT', 'cttttcata', 'ggatatttg', 'tgaaaaact', 'cttctttgt']
10 random kmers from KI270521.1 [Elapsed time: 00:00:00.00]
['TAATAAGAT', 'ATTTAAAGT', 'gggaatatc', 'acggaatat', 'attggaaac', 'GTGACTGTC', 'aaatggtaa', 'gtgatgtgt', 'TATTCACAT', 'ctttttgta']
10 random kmers from GL000195.1 [Elapsed time: 00:00:00.06]
['ACCTGGATG', 'tacttggga', 'ATTAAGTAG', 'tttattgat', 'TACAGCATT', 'GGAGATGAA', 'atataacta', 'attctctca', 'aaagatttt', 'tggatttgt']
10 random kmers from GL000219.1 [Elapsed time: 00:00:00.07]
['ATACAGCTT', 'TTGTTTGTG', 'tgacaaaca', 'atgcaaact', 'tgaaatcct', 'TGGGTTTCT', 'ACAACAGCC', 'AACAAATAA', 'ttcagctaa', 'tactatttt']
10 random kmers from GL000220.1 [Elapsed time: 00:00:00.06]
['aggaggcgg', 'agcgccacc', 'agaatcaga', 'GCCTTCCTT', 'GATGACAGC', 'GCTTAATTT', 'GAGggtatt', 'TATGAACTT', 'cactgtctc', 'ATGTACCTC']
10 random kmers from GL000224.1 [Elapsed time: 00:00:00.07]
['AGCTGTGTC', 'GGAGTTTGC', 'GTGTGCCTT', 'aaTTGAGAC', 'tgttttatt', 'GATATGTGA', 'tatcTCAGG', 'tgttttttg', 'tctggaggc', 'TCGGTGTTG']
10 random kmers from KI270741.1 [Elapsed time: 00:00:00.06]
['gagAATAAT', 'tgctacgag', 'gctgttgga', 'attccTTTA', 'tgcctgtag', 'aacaatgaa', 'TTGCCTGGG', 'agcaggagt', 'CTTAGCCCT', 'CTGGTTGAA']
10 random kmers from GL000226.1 [Elapsed time: 00:00:00.01]
['ggaagtgga', 'acattgcct', 'tagacagaa', 'taaagggaa', 'ttctcagaa', 'agcatttcg', 'cggtgaaaa', 'gatgtgtgc', 'agaccagct', 'cagaaacat']
10 random kmers from GL000213.1 [Elapsed time: 00:00:00.06]
['CACAAAGTC', 'AGAAAAACA', 'taacttaag', 'CATGCCAGC', 'ATGCCCCAA', 'CACTTTAAT', 'agcctaata', 'TATAGTTGA', 'taaggagat', 'gattcctag']
10 random kmers from KI270743.1 [Elapsed time: 00:00:00.08]
['atcatcctg', 'CCTACGAGG', 'GTCCATGTG', 'TCATGCCTG', 'TTTTATTTA', 'TCCACGCTG', 'CTCCAGTTG', 'ttgtttttt', 'gctgtaaca', 'AAAGTTATC']
10 random kmers from KI270744.1 [Elapsed time: 00:00:00.06]
['tcttaaaaa', 'tgagactcc', 'CGGGGGTGA', 'AGCCCCAGG', 'ggtggctca', 'AAACACAGG', 'gaacaaaga', 'CAAGAGTAC', 'GGAGGGGGC', 'TATTGGAGA']
10 random kmers from KI270745.1 [Elapsed time: 00:00:00.02]
['AAGATGAGT', 'attctacat', 'CACATATTG', 'atgcccatc', 'tgagggtgt', 'acagagtct', 'tttattctt', 'AGGAAGGGT', 'gtcaaacac', 'CCGCAGCCA']
10 random kmers from KI270746.1 [Elapsed time: 00:00:00.02]
['TCATCACAA', 'TCACTGATT', 'CAGCAAATT', 'gcaagagtt', 'caaaatggg', 'TTATCTTTA', 'ACATGTGCT', 'aatgtagtt', 'AATTAATCC', 'ACAGATTGC']
10 random kmers from KI270747.1 [Elapsed time: 00:00:00.07]
['actcttttt', 'aaaaggaaa', 'agactccat', 'atgattcca', 'catttcaag', 'cagaagcat', 'AAATtcctt', 'acagaagca', 'aaaatctag', 'cttttgata']
10 random kmers from KI270748.1 [Elapsed time: 00:00:00.04]
['cagcacacc', 'agtgaccac', 'gcatacacc', 'AACAGTGAC', 'GATATCAGG', 'AAAGCAATc', 'GAATCAAGG', 'ctggagagg', 'TGAAGAAAG', 'TAAAAGAAT']
10 random kmers from KI270749.1 [Elapsed time: 00:00:00.06]
['TACTTTCtc', 'CTCAAtagt', 'tataaagac', 'ccctggacc', 'tgaaatgag', 'AGGGAGGGT', 'CTGATAGCA', 'ACTGTATAT', 'tttaaaata', 'CTGGGCACT']
10 random kmers from KI270750.1 [Elapsed time: 00:00:00.06]
['GTTGTGCAA', 'TGTGATAAC', 'gctcactgc', 'gctggtatt', 'AGGTTAATA', 'TTCTTCTAT', 'ttttattct', 'TAGGATAGG', 'ATACTTAAG', 'ACCCAGAAA']
10 random kmers from KI270751.1 [Elapsed time: 00:00:00.05]
['GTCCAACTC', 'AGCGAGAGA', 'AGTTATAGA', 'GTTGGTAAC', 'ggtgatatt', 'TCACACTCC', 'TATTCCCAT', 'tagatatag', 'CTTGAAAAC', 'tgacaaaaa']
10 random kmers from KI270752.1 [Elapsed time: 00:00:00.01]
['CTCTTCCAT', 'aatcccgaC', 'ATATTGCCA', 'AGACCCAAG', 'AACAAGTCC', 'gctgggact', 'GCATGATCT', 'CTGCAATCA', 'TCATGGGTT', 'GACCCTGAC']
10 random kmers from KI270753.1 [Elapsed time: 00:00:00.02]
['GTGATTTTT', 'tggagtaca', 'CCCAGGTAT', 'CTAGTTCGT', 'CAACCCTAT', 'CATCATTAC', 'attttgtta', 'TGTTTTATG', 'gacaaaata', 'ttatataaa']
10 random kmers from KI270754.1 [Elapsed time: 00:00:00.01]
['tcctgacct', 'CGCTTTAGG', 'GCCTGCGTG', 'TCTTCTATA', 'TTTTTTTCT', 'GTGAGGCCG', 'TGATAAACC', 'GCATACGGG', 'GTGGAAGGG', 'cagagtCAT']
10 random kmers from KI270755.1 [Elapsed time: 00:00:00.01]
['gtttcaatg', 'GAAGCTAAT', 'TGAGctccc', 'GGACATGTT', 'GTCTGGCTC', 'AAGAGAAAT', 'GCTGATGTC', 'CCCACGCAG', 'GTGCCTGGC', 'CAACCCCTT']
10 random kmers from KI270756.1 [Elapsed time: 00:00:00.03]
['catttcatt', 'attccatac', 'attccactt', 'tccatccca', 'ttccattcg', 'tccattcca', 'ttccattcc', 'TTGATtgca', 'cattctatt', 'atatTCCAG']
10 random kmers from KI270757.1 [Elapsed time: 00:00:00.02]
['aggaataga', 'GAGAGGTTT', 'NNNNNNNNN', 'catctccaa', 'ttgtagaat', 'tttcctttt', 'ctgcaagtg', 'agaagtaat', 'gttttgaaa', 'NNNNNNNNN']
10 random kmers from GL000214.1 [Elapsed time: 00:00:00.05]
['tgccctggc', 'agagtagct', 'TCAAACTCA', 'AACCAAATT', 'agaggacac', 'AATGCAGCC', 'aaaatgcaa', 'gaGCATTTC', 'ATCAAGATT', 'GGGATGGCT']
10 random kmers from KI270742.1 [Elapsed time: 00:00:00.07]
['Atgcctata', 'ctcactggg', 'ttgaatctG', 'aaaacttta', 'gacgagtta', 'tatttctgc', 'ACCAGGGCA', 'ACCTGCTAT', 'TAAGGAGCA', 'gccctttgt']
10 random kmers from GL000216.2 [Elapsed time: 00:00:00.06]
['gtttacagt', 'cttgctctg', 'attccattc', 'CCTGCAGAG', 'tgattcaat', 'CTAGGAAAT', 'CATCCCTTT', 'CTCCCGGAG', 'cattgcatt', 'atgtcacaa']
10 random kmers from GL000218.1 [Elapsed time: 00:00:00.06]
['CAGGTTCCC', 'AAGGGCAAC', 'ccagaacat', 'TGCAATTTG', 'AACGCCTGG', 'ATAAAGATT', 'ATATTAGGA', 'atttgtgtt', 'catgaactc', 'GATCTGTTT']
10 random kmers from KI270762.1 [Elapsed time: 00:00:00.13]
['CTTCCCTCT', 'NNNNNNNNN', 'AGCACCCAT', 'CCCAAATCC', 'AGAGGTGGG', 'CCGTCACAC', 'gactggaac', 'CCAGATGGT', 'aagtgcagc', 'CCAGGTGCG']
10 random kmers from KI270766.1 [Elapsed time: 00:00:00.10]
['tcaaaaaat', 'TTCCTAGCT', 'TTGTCCTCT', 'gtgagactc', 'ttttccatt', 'ttttttttt', 'TAACGTTGA', 'agctgtaga', 'CAGGAAGAT', 'aaaaacaaa']
10 random kmers from KI270760.1 [Elapsed time: 00:00:00.04]
['gtgcctcaa', 'caacagagt', 'CCATGGGAC', 'GTCTCTCCA', 'ACATGTaga', 'ggggtggga', 'TTCCATATC', 'gggagggga', 'TGCTGTTAT', 'gtaGACCTC']
10 random kmers from KI270765.1 [Elapsed time: 00:00:00.07]
['CATCCCAGC', 'aaaatagtC', 'AACTCCCCA', 'TGATAATCA', 'TTGCACAGC', 'gcactctag', 'gctgaggaa', 'tcacatcac', 'GTGCAAAGA', 'taaacaagt']
10 random kmers from GL383518.1 [Elapsed time: 00:00:00.07]
['tgatcgcgg', 'CACTCAGAC', 'GGTCAACAT', 'TCTGCCACA', 'GTCCTTGCA', 'ggagggagg', 'AATCAAGAA', 'GTCTCTTCA', 'CACCTTTGC', 'TTAGGCCTA']
10 random kmers from GL383519.1 [Elapsed time: 00:00:00.04]
['GCAAAAACG', 'AGTGACAAA', 'GGCTCCTGG', 'TAAGTTTGG', 'ccAAAGgat', 'gctaatttt', 'ACAGGAGGG', 'tcaactaaa', 'AAGAAGGTA', 'ccagccagt']
10 random kmers from GL383520.2 [Elapsed time: 00:00:00.13]
['TGGGAAAAA', 'taaacaTCC', 'ATGTACTGA', 'gagaaaagg', 'TTTGCATGT', 'gataaatac', 'AGATTAAAA', 'TGGAAGCTT', 'TCTAGAGAT', 'tttctgttt']
10 random kmers from KI270764.1 [Elapsed time: 00:00:00.02]
['ctggatttt', 'aaaaaaaaa', 'GTTTCCAGG', 'CCCCGACAC', 'TTCAATGTA', 'TGCCAGGCC', 'caggcgcgg', 'ttggtggga', 'TGGGATGAA', 'taaAAACAA']
10 random kmers from KI270763.1 [Elapsed time: 00:00:00.33]
['AGCCCTGCT', 'cattttAGA', 'AGGATAGAG', 'GAAACCACA', 'AGTAAGAAA', 'ttAGGAAAT', 'TTCACTTAG', 'GTTTTAACG', 'TCCCCACCA', 'taatttaaa']
10 random kmers from KI270759.1 [Elapsed time: 00:00:00.18]
['taaagtgct', 'TTGtgcgaa', 'ctagaaaaa', 'TAAGCCAGG', 'TCAGAGGTG', 'TTTCTACCC', 'TATAATCAA', 'CTGCCTTTG', 'GCAAGAATT', 'GAGTTCAGA']
10 random kmers from KI270761.1 [Elapsed time: 00:00:00.06]
['ATTCCTGAA', 'CATACAAAC', 'TTGTTTCAA', 'CAGATGTTA', 'ACATTTTAA', 'GTGTGATCC', 'GTGAATTTT', 'TTTCAATTT', 'AGGATATAG', 'TCagtatat']
10 random kmers from KI270770.1 [Elapsed time: 00:00:00.05]
['AGTGTTGGA', 'AGAGGTCAG', 'CTGTGGTGC', 'CTCAATCAG', 'tgtttgttt', 'aaaataatt', 'GGAGTCACA', 'tggacacag', 'TCTTTCACT', 'aggacatag']
10 random kmers from KI270773.1 [Elapsed time: 00:00:00.03]
['TTCTGGCAG', 'cgccgcacg', 'AGGACAAAA', 'TCTTCCATA', 'TCCACCTCC', 'AGAAAGCAG', 'GTGTGTGCT', 'GTTTGtgtt', 'TGGGAACGA', 'CTCATTTGT']
10 random kmers from KI270774.1 [Elapsed time: 00:00:00.08]
['CAGACAGTT', 'AGTCTTCCA', 'cgttattta', 'AACGGGGCA', 'ggtgacaaa', 'CTCCAATGT', 'CAAGAACAG', 'TTTTTAAGT', 'CAACAGCCA', 'CAAATTACC']
10 random kmers from KI270769.1 [Elapsed time: 00:00:00.05]
['CATTGCAGG', 'TCTTAAATC', 'gaaaaaatg', 'GTAGTGGAC', 'TACCTTTGG', 'TGGCTGAAA', 'agaagtaga', 'TCACCATCC', 'ttttgtatt', 'ATGCGGGGA']
10 random kmers from GL383521.1 [Elapsed time: 00:00:00.05]
['ATTtctgaa', 'GAAAAATGT', 'ACCCTGATA', 'AATCTGTAA', 'tatcactgc', 'CATGTTGAA', 'CTTCTTTGG', 'TCTTAAAGT', 'agagtataa', 'GGTCCTGAa']
10 random kmers from KI270772.1 [Elapsed time: 00:00:00.05]
['atacccagg', 'attacaaTA', 'tatttttaa', 'aaatcaaaa', 'CTCAACATC', 'gattccatt', 'AAGCAGGAG', 'tattttact', 'ATTAATGAT', 'acctgaagt']
10 random kmers from KI270775.1 [Elapsed time: 00:00:00.05]
['TCTTCTCAG', 'gcctacttt', 'atataCTAG', 'tatcttcag', 'ttgactacc', 'ACAACATGA', 'cacaaatca', 'ttgttgatg', 'atatcttta', 'tctTATTGA']
10 random kmers from KI270771.1 [Elapsed time: 00:00:00.04]
['atcccatta', 'accagaaat', 'ACAACAAAT', 'TAGATCATA', 'CCAGGCCTG', 'ATAGGATTA', 'atatgtgtg', 'GATTTACCA', 'tgtgctaca', 'TTATGTGTC']
10 random kmers from KI270768.1 [Elapsed time: 00:00:00.04]
['AGAGACAGC', 'tcccagcac', 'TGGTGTCCC', 'CTGCTGAAC', 'atttgaacT', 'GATCACCAA', 'acatcaggc', 'CTATGTCAG', 'TGAAGGGGA', 'GACACTCAG']
10 random kmers from GL582966.2 [Elapsed time: 00:00:00.03]
['GCAGAATTC', 'GGCTTTGAT', 'gggcagggg', 'CTGCTCATC', 'aggggaggt', 'CACAGGCTG', 'ttggagacc', 'ggattattt', 'ACTCAGTGG', 'gagtaagtt']
10 random kmers from GL383522.1 [Elapsed time: 00:00:00.04]
['TGTCACCCT', 'AGCCAAGTG', 'aaacatata', 'TCAGCATCC', 'AGATTGTTC', 'GCACAACAC', 'GAGGGGCAC', 'CATCATTAG', 'CTTGCAGTG', 'GACTTATCA']
10 random kmers from KI270776.1 [Elapsed time: 00:00:00.06]
['agaacttaa', 'TAGAGTGCA', 'GTCTCCTGC', 'AAGTTGAAA', 'CTCCTTTCA', 'cgttagttt', 'cctccctcc', 'aatgTCATT', 'TAAAGGTGT', 'AGACTAACA']
10 random kmers from KI270767.1 [Elapsed time: 00:00:00.06]
['TTCATACTC', 'CTGGACAAG', 'TAAATAATC', 'ATTACTGAG', 'TAATGTTCC', 'ATCAAGACG', 'ACTAAGCAC', 'CCAGAGGAC', 'CTCTAAGCT', 'CCTTCGAGA']
10 random kmers from JH636055.2 [Elapsed time: 00:00:00.06]
['AAGAGCCTG', 'TAGATGGGC', 'ATCTGTTTC', 'GAGCCAACT', 'GGTAAAGAT', 'CTGGTGGCG', 'CTTCAAACC', 'GTAACACTG', 'agccaacag', 'GTTCCTGGC']
10 random kmers from KI270783.1 [Elapsed time: 00:00:00.04]
['ATTCCTGTA', 'GACCCTGCT', 'CCAGTTTTG', 'TGATTAATC', 'ACTGGGTCT', 'GTTTGGGca', 'Aactaaatt', 'AGTCCCAAT', 'tttctttat', 'ttggggagg']
10 random kmers from KI270780.1 [Elapsed time: 00:00:00.08]
['CTTCTTATT', 'TGGGCCGTC', 'tccttgaga', 'aaaaaagcc', 'CTCACCCCA', 'CCTCCCTTG', 'CTCTGGAAT', 'gacggggct', 'TTTCTCTAA', 'gcttcccaa']
10 random kmers from GL383526.1 [Elapsed time: 00:00:00.07]
['GGCCCAAAC', 'CAGGTATGC', 'agaaaaata', 'gttagaatg', 'agccaccat', 'TCTGGCTCC', 'gtggttatt', 'tattttaca', 'atgtattaa', 'ttttttttt']
10 random kmers from KI270777.1 [Elapsed time: 00:00:00.06]
['CAATCCTGG', 'GTGGGGAAG', 'ATATCTTTA', 'aaagcatat', 'CTGGTACTT', 'tgacaaaca', 'ttgggaggc', 'ttctttttt', 'AACATCAAG', 'TTTAGACCG']
10 random kmers from KI270778.1 [Elapsed time: 00:00:00.09]
['GTGGCAAAG', 'CCTCTCATA', 'tattctatt', 'aTCCTGGGA', 'TAACATTAT', 'TACATCTTT', 'TACTGTTCT', 'CTAAGATTG', 'CTGGCACCC', 'ATTATCCTT']
10 random kmers from KI270781.1 [Elapsed time: 00:00:00.04]
['TCCAGCTGC', 'gtgcagtgg', 'aggcatggt', 'tccatggat', 'TCTTTAGTT', 'GATAAATCA', 'CCACCCCTA', 'TTCTTCCCT', 'tgcctcctg', 'AGTCTAGAC']
10 random kmers from KI270779.1 [Elapsed time: 00:00:00.07]
['TTGCAAATC', 'GCAGAGGGC', 'CCCCCAGTG', 'CCTCATATA', 'CCCCGAACC', 'tgcgtcact', 'GGAATCTAA', 'GGAACAATG', 'TACTCCCTA', 'TCACGGGGA']
10 random kmers from KI270782.1 [Elapsed time: 00:00:00.06]
['CTGGCCCCT', 'CAGGATGGA', 'cctctccag', 'GATGTTGCA', 'tagagacgg', 'AGAGCCAGG', 'ggtggttgt', 'CTCTAACCC', 'CACCCAGCT', 'caTTGGCAG']
10 random kmers from KI270784.1 [Elapsed time: 00:00:00.06]
['AAGAAATTA', 'GGGTTCTGG', 'TGAATTCAA', 'acactcgcc', 'TTGTATCTT', 'AGAGTTGGA', 'TTAATaacc', 'gtggccagc', 'aataattgg', 'CAGGCTGTA']
10 random kmers from KI270790.1 [Elapsed time: 00:00:00.08]
['AGCTAGAAA', 'taagCAACT', 'AAAAACAAT', 'AATCATAGT', 'ACAGAGGTG', 'GGGATTAAC', 'caaacttag', 'TGTACAAAA', 'TTCTGCCTA', 'GACTGCAAA']
10 random kmers from GL383528.1 [Elapsed time: 00:00:00.14]
['AATAGATAA', 'AAGGACAGC', 'TCATTCCGA', 'GAATAAATT', 'Aaatacctg', 'TTAATAATC', 'ACAAGGACT', 'GGAATATTT', 'GTTCCTCTG', 'ttttttttt']
10 random kmers from KI270787.1 [Elapsed time: 00:00:00.04]
['agaagtcat', 'aatttaaaa', 'atggaatac', 'CCTAATAAT', 'TATTTACCT', 'GAAGGGTTT', 'TTATTCCAG', 'TCTTAGAAA', 'AGAAATCAT', 'TAATGGTCA']
10 random kmers from GL000257.2 [Elapsed time: 00:00:00.21]
['AGTCTCCTT', 'tagctgaac', 'ATGTTAGTA', 'GACAGTTTT', 'Tcttatttt', 'agtggctca', 'aagtttttc', 'ttcaTCTAT', 'tttctcttc', 'TCTGAGGGG']
10 random kmers from KI270788.1 [Elapsed time: 00:00:00.07]
['TGTTGAGCC', 'Atgtgatta', 'cccaagaAT', 'CCCCAGAAG', 'GGGCCTGAG', 'cacacaggc', 'cagctaatt', 'cctttgaTG', 'tttgaaaaa', 'aaatggACT']
10 random kmers from GL383527.1 [Elapsed time: 00:00:00.06]
['ttctcattg', 'CACTAAGTA', 'CTTTTAAAC', 'AAAGTATGC', 'gtatcttgt', 'ATTATATTG', 'ttgacctcg', 'aaaatgaat', 'ATACGTAAA', 'actcctgag']
10 random kmers from KI270785.1 [Elapsed time: 00:00:00.04]
['CCTGTCTCT', 'GGAGTTTAA', 'GGAGCAAGT', 'GTATCTTTT', 'GCCTTaaca', 'ttcatcaac', 'ctgcctcag', 'AGTTATCAT', 'TATATCAAT', 'TTAGTGCAG']
10 random kmers from KI270789.1 [Elapsed time: 00:00:00.07]
['AACATCCAT', 'aatggggaa', 'GGGGGCCAC', 'ATTACCTGA', 'TGTAAGATG', 'acttttggc', 'GATTGTTGT', 'CTTGAGGAA', 'TGTACTCAA', 'aagaaagaa']
10 random kmers from KI270786.1 [Elapsed time: 00:00:00.09]
['CTAATTTCA', 'GTACATTCC', 'GGGAAATAA', 'GCAGGTATT', 'TAGCAGGTA', 'CAATTCTGG', 'AAATCCTTA', 'tgagaccag', 'AACTCTGGC', 'atgcctgga']
10 random kmers from KI270793.1 [Elapsed time: 00:00:00.05]
['GCACTCGCA', 'TGGCTGGCA', 'TGagtgagt', 'TCCCGTGAC', 'AGTGGCGTG', 'CTGGTGGAT', 'CCCAGCACT', 'CTCCAGGCA', 'TGCCGGGCC', 'ACCTGCTGG']
10 random kmers from KI270792.1 [Elapsed time: 00:00:00.06]
['ggctgagag', 'CCTGCCCTT', 'TTTGGGTTC', 'TGGGGGGCA', 'CAGTGTTTC', 'CCAGGTGAG', 'GCACGGGCT', 'AGTGTGTGA', 'CCCGGGAGC', 'ttgcatcac']
10 random kmers from KI270791.1 [Elapsed time: 00:00:00.07]
['CCTGGTGCA', 'TGGGACAAA', 'CCTGTGGTG', 'ACAGACCAA', 'CTATCCCCG', 'ATTTTCCTC', 'CCTTTAGTT', 'TCTAAGCAG', 'ACAGTCCTC', 'ctctctgta']
10 random kmers from GL383532.1 [Elapsed time: 00:00:00.03]
['ctgcctaca', 'aatcaagtt', 'CACATTACA', 'TAAAGGTGA', 'atatgtaaa', 'GGAGAGAAC', 'ttttcttct', 'TAACTTTAT', 'gaatgttct', 'TGTGGCATC']
10 random kmers from GL949742.1 [Elapsed time: 00:00:00.08]
['ATGATAGGA', 'cccgggagg', 'aagtaaaat', 'cctcctggg', 'TCTTATGTA', 'taaaaatta', 'GGACCAAGT', 'atctctgag', 'ttaaaatac', 'GAACtatgt']
10 random kmers from KI270794.1 [Elapsed time: 00:00:00.06]
['TTCCAGGCA', 'CAAGTCCTC', 'gtttggttt', 'GTTCACTGA', 'aacaatatt', 'GTAGATCTA', 'CCATATTGa', 'gagacaaTA', 'aaagaaatt', 'ATTGCCCTC']
10 random kmers from GL339449.2 [Elapsed time: 00:00:00.59]
['ccccatctc', 'attaggaaa', 'GATAGTTTA', 'ctctacttt', 'TCTCTAAGC', 'NNNNNNNNN', 'TGTTATTCC', 'atttaaagt', 'TAAGCCTGC', 'tttttgtat']
10 random kmers from GL383530.1 [Elapsed time: 00:00:00.07]
['cccaagaaa', 'CATAGCGAT', 'tttaaTGGC', 'GAAAAttcc', 'GCAATTAGG', 'atcagaaaa', 'gttgcttcc', 'AGTTCAGTG', 'attgatttt', 'TTTCTGTCT']
10 random kmers from KI270796.1 [Elapsed time: 00:00:00.06]
['TTGTAATAT', 'CTGTTTTAG', 'GCCAGATGT', 'ACACAGCAT', 'GGGCATTCA', 'TTGGAGTTT', 'GCGCTAGGT', 'tcattttga', 'GCACTAACT', 'AAGTGAATG']
10 random kmers from GL383531.1 [Elapsed time: 00:00:00.06]
['AAACTTTTA', 'TATTTCTGt', 'aaatgaaat', 'atttttctt', 'tataatata', 'atcagagtg', 'TCCCAAGAT', 'TTTGACTGT', 'TACGATGAG', 'AAATAAAGA']
10 random kmers from KI270795.1 [Elapsed time: 00:00:00.05]
['ctggaacct', 'tggttttga', 'GTCCATCCA', 'CATTATTGC', 'acagaaaac', 'TCTGCAGGT', 'TTGGGTTTT', 'aaaaaaaaa', 'CTTTAAGTT', 'ctcatactc']
10 random kmers from GL000250.2 [Elapsed time: 00:00:01.75]
['CAGGTCAGT', 'NNNNNNNNN', 'CGCCTGGTG', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'ttttactgt']
10 random kmers from KI270800.1 [Elapsed time: 00:00:00.18]
['taaaaatcc', 'ggtttttaa', 'GAAAATTTT', 'ctcaagaaa', 'GACGATGCC', 'GCAAAGACT', 'aCTAGCATA', 'tatataaaa', 'tcttgttga', 'ACTGGTAAG']
10 random kmers from KI270799.1 [Elapsed time: 00:00:00.05]
['aatcaacat', 'atgtcaaca', 'tacctccag', 'ttagattgt', 'tggataaaa', 'AACAGAGAG', 'CCTAATAGT', 'tgggatttt', 'ttatgaaat', 'ctgcctcaa']
10 random kmers from GL383533.1 [Elapsed time: 00:00:00.04]
['CAGAGTGTG', 'GAACTACAG', 'GCACCTTCC', 'ACGGAGGGC', 'cactgcaac', 'atgattatt', 'CCACTCACT', 'CTCTCAGGG', 'ccctcagct', 'CCACtcagc']
10 random kmers from KI270801.1 [Elapsed time: 00:00:00.32]
['AGAGCACTG', 'acaccagtt', 'aaaaagtca', 'TTAGTAAGG', 'AGGAAATGA', 'GTCTGAATT', 'gaaggacat', 'TTAGTTAGT', 'tttttaaaa', 'AGGAAAAAA']
10 random kmers from KI270802.1 [Elapsed time: 00:00:00.05]
['TTCTTCCCA', 'AAGCCAAGG', 'AAAGGAAAT', 'AAAGGGAAT', 'TGTCAGGCT', 'TGGACCTTT', 'TAAAGGCtt', 'CATATTTTT', 'tatgtacat', 'TGAGTGTGA']
10 random kmers from KB021644.2 [Elapsed time: 00:00:00.06]
['AGATGGCAT', 'CTCACCTCC', 'GCTGATGAG', 'TGTGGAGCA', 'ctaaaaaaa', 'CCCTGTCAG', 'agcgattct', 'aaggagaga', 'CAAATTAAA', 'gacactgcg']
10 random kmers from KI270797.1 [Elapsed time: 00:00:00.07]
['AATCCCTTC', 'GCCTTTCCA', 'AGGAGGTCA', 'CTACAGATT', 'taatcccag', 'cctcccaaa', 'ctgtgcttt', 'tataatact', 'ACCTCCCAG', 'agataggat']
10 random kmers from KI270798.1 [Elapsed time: 00:00:00.10]
['GGTGCCGTG', 'CAaacactt', 'gagactttt', 'caggaggtg', 'GTCAGGCTA', 'CGCCCATTC', 'CGGCTTCCA', 'AGAGAGTTG', 'GGTAGCAAA', 'CTGACTGAC']
10 random kmers from KI270804.1 [Elapsed time: 00:00:00.06]
['GCCCATCAG', 'GCCCTGTTC', 'GGACACAGA', 'CCATTCATT', 'GACAAAGGC', 'CAAGTGCTA', 'ACAGAAAAC', 'CTGTAAGAA', 'tgtggattt', 'GAATTGCTG']
10 random kmers from KI270809.1 [Elapsed time: 00:00:00.07]
['ggctccacc', 'CAATAAAAC', 'attctcctg', 'tgagaTAGC', 'ATATGAACA', 'gaggaattt', 'gaagaccag', 'TGGGAAATG', 'CACACCTGC', 'GGAGCCCAG']
10 random kmers from KI270806.1 [Elapsed time: 00:00:00.05]
['GAATGTTAA', 'cacactttg', 'aggattgct', 'CCTAGCAAA', 'TAAATAGCT', 'tttagttgt', 'TGATAGAAG', 'CCACATAGA', 'TTCCAGGCA', 'gtgcatgtg']
10 random kmers from GL383534.2 [Elapsed time: 00:00:00.04]
['ctgcatgca', 'TTAGTCAGT', 'CTTAAAATA', 'CCAAAGTGG', 'catatattt', 'GATTTTCAG', 'TATAAATTC', 'TGTCCATCA', 'ATCTTAGTG', 'TCCCCTATC']
10 random kmers from KI270803.1 [Elapsed time: 00:00:00.40]
['TGAAGACAT', 'GCCTCCTGC', 'CCTTCCGGG', 'ctgcatttc', 'TAGCTAGTT', 'TCTTTATTC', 'GGGTTGGAG', 'CCAGGAGCT', 'ACAGGAGAG', 'ggaggtagg']
10 random kmers from KI270808.1 [Elapsed time: 00:00:00.12]
['tgggattac', 'actcctaac', 'ataatagac', 'GCAAAACGT', 'AAAACATCT', 'ATCCCCCAA', 'tctagctaa', 'TATTGCAGC', 'CCTGGTTTT', 'GGGAAATGG']
10 random kmers from KI270807.1 [Elapsed time: 00:00:00.05]
['GAACGTGCG', 'catgctcat', 'tatttgttt', 'TTCCTATTC', 'AAATCAGTT', 'ATCTCCTCA', 'GGCAcagcc', 'CTGAGCTGT', 'ACAGGCTGT', 'CCCACCACG']
10 random kmers from KI270805.1 [Elapsed time: 00:00:00.07]
['GGTTTGGGT', 'GTGTGTGTA', 'CTTCCGGGT', 'gctcttccc', 'AGCGACTGG', 'catATGTCA', 'GGGGCCCAG', 'tttagcctG', 'CATCCTGGA', 'tgtgaggga']
10 random kmers from KI270818.1 [Elapsed time: 00:00:00.05]
['AGGGGTGAA', 'CCCAGAATA', 'GCTGCACAG', 'CAAATCCTT', 'AAGCTGGTA', 'tgcctccca', 'CATAGTGTA', 'gagatcgag', 'CGGCTGGAG', 'AACACGACG']
10 random kmers from KI270812.1 [Elapsed time: 00:00:00.10]
['GTTTTGGCT', 'ATTCCTGCC', 'tctgttttt', 'GATCAGGGT', 'GGGCTCAGG', 'TCAGACTGT', 'Atcctttat', 'TTAAGGAAC', 'ATTTTTGTA', 'GGAGGCAGT']
10 random kmers from KI270811.1 [Elapsed time: 00:00:00.11]
['ggctGAGAG', 'CTCATGGTA', 'TCATACCTC', 'aagagagaa', 'atgagacct', 'CACATTCAC', 'ATTACTGAC', 'AGGTCGTCT', 'CCATATTTC', 'CTGTGCTGC']
10 random kmers from KI270821.1 [Elapsed time: 00:00:00.36]
['GTGATTTGC', 'GCATCATGT', 'caGAGGAGA', 'GTGCTGGAG', 'GTCACACGG', 'CAGAGGGCA', 'ATGAGGGCC', 'agcAAGTTG', 'TCTGGTCCC', 'ACATAAGCA']
10 random kmers from KI270813.1 [Elapsed time: 00:00:00.13]
['CCtaagttt', 'CATTTGGTT', 'agcacagac', 'aaagaggaA', 'GACATCCGG', 'AAACAGAGA', 'aaccccgtc', 'tctagggct', 'CAAATTCTA', 'ACCCAATAT']
10 random kmers from KI270822.1 [Elapsed time: 00:00:00.23]
['ATTCTTTAC', 'tctgtaatc', 'tgtggtccc', 'TCATCCTAT', 'aatctttat', 'ataTACCCA', 'ACCCCaaaa', 'taatataca', 'atagATAAA', 'AAGAAGCTT']
10 random kmers from KI270814.1 [Elapsed time: 00:00:00.06]
['agcaaaata', 'tacataatg', 'ATGAGGTCA', 'agggcatta', 'AGAACATCT', 'AGGCAATCT', 'CTTGTCAGG', 'GCCATAGGC', 'GAAATGAGC', 'ACATATATA']
10 random kmers from KI270810.1 [Elapsed time: 00:00:00.13]
['cactaactc', 'ctaaaaata', 'gggcagagg', 'ATTTTAGAA', 'CTACAAAAT', 'TTACACACT', 'ATTAGAACC', 'TTCAAGGAC', 'TCTGTGATC', 'TACTCCACT']
10 random kmers from KI270819.1 [Elapsed time: 00:00:00.05]
['GCTGCTATA', 'CCACCTAGT', 'tttatatcc', 'AGTGTGAGG', 'gtctggctt', 'CCCTCCTGT', 'CGGCTCAGC', 'CCGAGCCCT', 'CTCCCTCAG', 'CGGGCACAG']
10 random kmers from KI270820.1 [Elapsed time: 00:00:00.01]
['TCCAAACCA', 'TTTTATGAC', 'GCATGACCA', 'GCTCCTTCC', 'GGGAATCCA', 'agaacaagT', 'GTTGCAAAA', 'GGGTGGCTG', 'TGACTAGTT', 'AGGAACCAG']
10 random kmers from KI270817.1 [Elapsed time: 00:00:00.05]
['GTTAAAACA', 'TGCTGCCAC', 'accatcacg', 'tagaaaagg', 'ACGCAAGCA', 'GCCAGGCTG', 'CAGCCTCCT', 'GCCCCctgc', 'CCGGAGCCG', 'CACACAGGG']
10 random kmers from KI270816.1 [Elapsed time: 00:00:00.11]
['CGGGGAAGG', 'CTGTTTGCT', 'GGCTGGCAG', 'CTGTCACTA', 'CCGACTCTC', 'CCAAATCCA', 'GAGAGTGGA', 'ACGGgttga', 'CTGACCCCT', 'gcccagcta']
10 random kmers from KI270815.1 [Elapsed time: 00:00:00.05]
['tgtgattca', 'ACAtactaa', 'TGTactgca', 'gcactttgg', 'caatggcaa', 'CTGTTGGAA', 'cactgcaac', 'CATGCCCCA', 'ctctcctgc', 'tgagatcgc']
10 random kmers from GL383539.1 [Elapsed time: 00:00:00.06]
['tcattttat', 'ATTTTGAAT', 'CCcctcttg', 'GGGAATTTC', 'TCCTATTCC', 'GGTATAACA', 'cacaagttt', 'GATGGATTT', 'GTCAGGTCA', 'TATTATTGT']
10 random kmers from GL383540.1 [Elapsed time: 00:00:00.03]
['GACAAAGGG', 'TTTGCGCCC', 'CAGGATGAG', 'TGCTAAAAA', 'AAGTGGTTC', 'GTGGGGACT', 'GGGCCaaat', 'tctttgtgg', 'gtgcctttt', 'GAAAACCAT']
10 random kmers from GL383541.1 [Elapsed time: 00:00:00.06]
['aacttgccc', 'ctctgaccc', 'GCCCAGCCT', 'GATCATTAG', 'tagaaatat', 'ttcttctgc', 'tggaagggg', 'TCTGccctc', 'agcttttga', 'ACTGCAGAC']
10 random kmers from GL383542.1 [Elapsed time: 00:00:00.02]
['CAACAAGGG', 'tgtctccaa', 'AGATTTCCA', 'atctccctt', 'CCGCCTTAG', 'tttggatat', 'tgaaccggg', 'CACTAAAGC', 'AAAGACAGC', 'ATTCATTTT']
10 random kmers from KI270823.1 [Elapsed time: 00:00:00.15]
['GATTCCACT', 'TCTAGAACA', 'GTTCCATTA', 'ATGTGTGAG', 'CTGTGACAC', 'CTGGTTCTG', 'tatatttat', 'TGTTTTATG', 'aacacatac', 'AGGTTGCTT']
10 random kmers from GL383545.1 [Elapsed time: 00:00:00.07]
['tagtCCTTC', 'CTCAGGTGT', 'tTTACagac', 'GAAAGGACA', 'TGGATATAC', 'CAAACTACC', 'gtacttttt', 'CTCTGGGGT', 'cagaactGA', 'gggctgaga']
10 random kmers from KI270824.1 [Elapsed time: 00:00:00.06]
['caggtggga', 'Caatatgtt', 'TTTGCATTT', 'tcctttcca', 'gtctcaaaa', 'attttgttg', 'ATATAACCA', 'TCCTCACTG', 'ctaacatat', 'GTGTTATGC']
10 random kmers from GL383546.1 [Elapsed time: 00:00:00.11]
['ATACCCCAT', 'TCTGGTTAG', 'tggagtgca', 'TTGTTCTTG', 'aagaaagca', 'GGCCAAGCA', 'TCTCTGCCT', 'CCATAGCGG', 'aaatcatat', 'TGGAAGGAT']
10 random kmers from KI270825.1 [Elapsed time: 00:00:00.07]
['GCCATGAAA', 'tctgagtta', 'GCCATTAGT', 'GTCaataga', 'GGGCCAATG', 'GGTGGTGGC', 'ACAAGGCAC', 'gtagtccca', 'TGGCAGGAC', 'TTCATCACA']
10 random kmers from KI270832.1 [Elapsed time: 00:00:00.07]
['gctttattg', 'caaaaacaa', 'gcctccctg', 'GCTTTAGAG', 'tcttgaact', 'TGGTGACTG', 'tttcagaGA', 'CCAAGCAGC', 'CCACCACTA', 'GCCATAGTG']
10 random kmers from KI270830.1 [Elapsed time: 00:00:00.06]
['TGTATCAGG', 'TCTGCCAGC', 'GCAGAGGAA', 'CACAGAATA', 'TTACATAGA', 'AGAAAATAC', 'CAGCAGGTG', 'GAGGACCTG', 'CTTATATTC', 'ccgggctgg']
10 random kmers from KI270831.1 [Elapsed time: 00:00:00.10]
['TTCCATGGA', 'TGAGAGACA', 'GGCAGCATT', 'AGCCCTTAA', 'gagataaac', 'gAAGTCTCT', 'TTGTGTAAA', 'TTAGCGGGG', 'CTGCTCAGG', 'GACAGACCC']
10 random kmers from KI270829.1 [Elapsed time: 00:00:00.07]
['actatacaa', 'ttgattgtg', 'GATAAGTGA', 'TCAGAGCTG', 'TTGTTTTAT', 'TGCCAGATT', 'CCCAGGCAG', 'TTTAATGAC', 'AGTACATAG', 'CTATCTACA']
10 random kmers from GL383547.1 [Elapsed time: 00:00:00.05]
['tcttggagt', 'CCAGTGTAA', 'ATGTTATAG', 'tattgtttg', 'CTCAAATCC', 'CTAGGTAAC', 'TCAGCCACG', 'AAAGTTGGG', 'TAAAAAAAC', 'gaaaattat']
10 random kmers from JH159136.1 [Elapsed time: 00:00:00.07]
['ATCTTTAGT', 'CTGTAAGTG', 'taatggatc', 'CAGCTTCCA', 'gggaatgga', 'CCACCAGGG', 'aaggacatt', 'AGGTCatta', 'ttttgtcat', 'attcacaca']
10 random kmers from JH159137.1 [Elapsed time: 00:00:00.07]
['GCTTACAAA', 'gaggtcTTA', 'aaattaatt', 'ggctatttg', 'CCCAAAACA', 'ttgggctga', 'TACAGATGA', 'CGAGTGCTA', 'GCCAGATAT', 'GGGACAGAG']
10 random kmers from KI270827.1 [Elapsed time: 00:00:00.03]
['AAACACAGC', 'TGGAAGGCA', 'GGAGGAGtc', 'AGGGACAGG', 'GGGGGCACA', 'TTTTTTTCT', 'AACCCACGG', 'AACGGGTCC', 'ccaaagtgc', 'tgttactga']
10 random kmers from KI270826.1 [Elapsed time: 00:00:00.06]
['CTATTATCA', 'taacaaaag', 'TAGACCTTA', 'TTAGGTAGA', 'GTTAGATGG', 'ggagtgagg', 'TAAACtaaa', 'AGATAGAAG', 'aagttttaa', 'AATACATTA']
10 random kmers from GL877875.1 [Elapsed time: 00:00:00.06]
['CTTCCACCA', 'acactaaCC', 'CATGCACAT', 'TCAGTTACC', 'TGGATTGAA', 'aaaatacaa', 'AAGGGATCT', 'CACAGTCAA', 'TCAGCAAGC', 'GTGGCTAGT']
10 random kmers from GL877876.1 [Elapsed time: 00:00:00.14]
['tggaaaact', 'ACACTGCAA', 'TCATGAGAA', 'GCTATGGTT', 'gtgtggtag', 'AGTTTAATT', 'AGGCAGGTT', 'tttatgtag', 'GTAAACGGC', 'gagaaggag']
10 random kmers from KI270837.1 [Elapsed time: 00:00:00.02]
['CTTGGGCTT', 'TGGAATGTG', 'tctcactca', 'ctcattttg', 'ACAGGTCCT', 'Agtaaaatc', 'CCATCAGTT', 'AAAAATGTA', 'CAAGGGAGA', 'TTCCCGGGT']
10 random kmers from GL383549.1 [Elapsed time: 00:00:00.04]
['AACACCAAG', 'tttgtgttt', 'AGTAAGCTA', 'TTCTGGCTT', 'GTGAACCAG', 'ATCAAAAGT', 'AGTTCTCAT', 'TGCTAAGTC', 'GCCAGAATC', 'cTGTCACAT']
10 random kmers from KI270835.1 [Elapsed time: 00:00:00.08]
['tatacaagt', 'TAGAAATTA', 'AACCTTTAT', 'AAGCACTAT', 'gtgattttt', 'TAGTtttcc', 'TCTCCTGCT', 'TTATGTTTG', 'GTCAAAGAA', 'taggacccc']
10 random kmers from GL383550.2 [Elapsed time: 00:00:00.06]
['gggagggac', 'GCCCACCCG', 'aagaaaaac', 'CTCGAATTA', 'TTCATTTTT', 'gtagCCTGA', 'GTATCTAAA', 'ATTGctaca', 'CAGTTTGAA', 'tcatgctac']
10 random kmers from GL383552.1 [Elapsed time: 00:00:00.05]
['ttttacaaa', 'AAAGGCATG', 'attttttca', 'ccATTGTGT', 'atatagatg', 'GTTAGCTTA', 'GCCACCATA', 'TACTTTTGC', 'AGATTATGc', 'aaagatttt']
10 random kmers from GL383553.2 [Elapsed time: 00:00:00.05]
['AGTGGAGAA', 'tatttttaa', 'cccagctac', 'AATGAACTG', 'gcagcgGTA', 'CCTTCCTCA', 'gatgaaccc', 'gaaaatcta', 'tggaaatac', 'TCTATATGA']
10 random kmers from KI270834.1 [Elapsed time: 00:00:00.04]
['AAATTTCAG', 'AACCATTGA', 'ccagtaatc', 'CTGGGCGCT', 'aggtggacC', 'gtggggagg', 'CCAGACGGT', 'atttaaaat', 'ttagagaca', 'aaaaatatt']
10 random kmers from GL383551.1 [Elapsed time: 00:00:00.06]
['CAGAGGTAG', 'ATCACCTTC', 'TCAAtaaca', 'gacatgCAG', 'ggtctttga', 'aatcccatt', 'accTTCAAT', 'AGAAAGGAG', 'AACACTGAG', 'ATCACAGAC']
10 random kmers from KI270833.1 [Elapsed time: 00:00:00.03]
['CTACCACCT', 'CATCCCAGT', 'AGCTTACTT', 'TCAGGCTGC', 'GAGACAAAC', 'TGTGACTAA', 'GTCAGTGAT', 'ACGCCGTTT', 'GCTTTGGAA', 'ATGGgctta']
10 random kmers from KI270836.1 [Elapsed time: 00:00:00.02]
['ATACACTGA', 'GACCCGGCA', 'ggtttattc', 'Gcctgtctc', 'AGTAAGACC', 'GGTGTAGTC', 'AACACTGGA', 'atagctgcc', 'CTCTGAACT', 'TGACCCAGT']
10 random kmers from KI270840.1 [Elapsed time: 00:00:00.06]
['TAAATGGCA', 'TTTTACAGG', 'CACTTAATA', 'aaacgtttt', 'TCCATTTGA', 'TTCATAGGA', 'AAGTTTTAT', 'aatataagt', 'TCACTAAAA', 'CATGTCATA']
10 random kmers from KI270839.1 [Elapsed time: 00:00:00.06]
['ACAACTTTA', 'GGATCTATC', 'AATATACAa', 'GAAAAGTGA', 'TAAAGAAAT', 'TAAATTTGT', 'TAACACTGA', 'GGAGGATTT', 'aaacacaaa', 'GGAATCAGc']
10 random kmers from KI270843.1 [Elapsed time: 00:00:00.04]
['GCATCAAAA', 'ATATCAGTA', 'TTgtatata', 'GTTATGAGA', 'TTTACTATA', 'GGTATCTAC', 'AGGTTGAGA', 'tctctcttg', 'CCTCCTGGT', 'GCCATAAGA']
10 random kmers from KI270841.1 [Elapsed time: 00:00:00.06]
['GAGGAAAGT', 'AAGGTCTGA', 'CCCTTCCCC', 'AGTGAATTA', 'AGTttttac', 'TCCTGTGGA', 'attaggaga', 'tttccgcag', 'ATTCAGAAA', 'TGCTACGTG']
10 random kmers from KI270838.1 [Elapsed time: 00:00:00.10]
['ATTTGATTT', 'ATCCATCAG', 'GCTTGAGCC', 'agtgtggac', 'AAGAGTCGC', 'ggagccagg', 'gaTTTTAAt', 'GCTCTCTTC', 'aatgccCCC', 'aactctgcc']
10 random kmers from KI270842.1 [Elapsed time: 00:00:00.02]
['cgctgccat', 'TCGTCCCGT', 'GCGGGACTG', 'AGGAAGAGC', 'AGGCAGGCA', 'TGGACTCTT', 'AATGGTCAC', 'TCTGCGCTG', 'ctctgcccc', 'ttcatcatc']
10 random kmers from KI270844.1 [Elapsed time: 00:00:00.11]
['GAATGTata', 'GTGCCCGCT', 'gccctgacc', 'ATGGGCTGA', 'tggtgcaat', 'cttctttgt', 'CCCCAGACA', 'gaaaaaaaa', 'aattcaata', 'AAATTTACG']
10 random kmers from KI270847.1 [Elapsed time: 00:00:00.56]
['TGTGGTCTC', 'CCTGCCCCA', 'CTGTGAGCT', 'ATTATGCAT', 'CAAAGCTGA', 'TATGTAGTT', 'CCTACACAC', 'ggaaaaaga', 'aaacagtaa', 'acTCTAGAT']
10 random kmers from KI270845.1 [Elapsed time: 00:00:00.10]
['CCAACCACC', 'CTGTGCCTG', 'CCCTGAGTC', 'AGCAGCACC', 'CGGAGCCTT', 'gttgcagtg', 'GGATCCCTC', 'CTGAAATGC', 'TGACTTGGC', 'TGCAGGGTC']
10 random kmers from KI270846.1 [Elapsed time: 00:00:00.49]
['AGCTATACC', 'GGAGTTGTC', 'CATACACAG', 'CCCGCCACC', 'attcttctt', 'TACCCaccc', 'ctgatatgg', 'CCGTCACTG', 'aggaTTACT', 'ATGCAGGGA']
10 random kmers from KI270852.1 [Elapsed time: 00:00:00.20]
['tagtcccag', 'cagagaccc', 'tattacTAT', 'TGCATCACT', 'ACTTGTATT', 'atcctttgc', 'GCCATATAG', 'TAAATGTAG', 'attttgatt', 'TTCAATTTC']
10 random kmers from KI270851.1 [Elapsed time: 00:00:00.10]
['ggaggctga', 'gccaggctg', 'GCCAGGGAC', 'aacaaataa', 'GCTGGAGAC', 'aaaatgtcc', 'CTGATCATA', 'TTTGGGGGT', 'GGCTGAGAT', 'ggggaggca']
10 random kmers from KI270848.1 [Elapsed time: 00:00:00.12]
['agaaaatta', 'ttttagtag', 'TCAAGCAAG', 'AGGCTCCAT', 'CTGGTGAAA', 'aaaaaaaaa', 'tcccagcac', 'TTCTGCGAT', 'CActgaaat', 'GGATATTGA']
10 random kmers from GL383554.1 [Elapsed time: 00:00:00.11]
['ACTCCTAGT', 'atatatgta', 'ATGAAGAAA', 'taacctgag', 'TTCCGAGAt', 'acaggcaca', 'GGAAACCTC', 'TTTCATAGA', 'AATAATGGC', 'AAGGTCTGG']
10 random kmers from KI270849.1 [Elapsed time: 00:00:00.09]
['TCCTCAGGT', 'GGAGGCTAC', 'AGTGGAGAT', 'tggtagaat', 'TGGAAGGCA', 'TTGCATTGG', 'GATTTTTGG', 'TAGGACAGC', 'TTTATTAAG', 'TCTTATCCA']
10 random kmers from GL383555.2 [Elapsed time: 00:00:00.14]
['aggatggtc', 'GTGCACTTG', 'CTCCTCCTC', 'AAGTCTCCA', 'CACTTATGT', 'TAACATACT', 'TTCTCCAGA', 'GACACTGGG', 'TCAGTCAGA', 'CTTCATTCT']
10 random kmers from KI270850.1 [Elapsed time: 00:00:00.16]
['ACCACAGAG', 'ATTCAGAAA', 'ccagcctgg', 'ttttttttt', 'CAGTCAGCC', 'TTTGCAAGT', 'CATGACCTC', 'GTGGCTGCA', 'AAGATTTAT', 'acctcaagt']
10 random kmers from KI270854.1 [Elapsed time: 00:00:00.05]
['AAGGTGGCA', 'AGGAGCAGA', 'GTTCTGAAA', 'GCAGGGCTG', 'TGTGATCTT', 'tgcattgta', 'tgattgatA', 'CCAGACCCT', 'TCATGGGCA', 'GGTGCGGGC']
10 random kmers from KI270856.1 [Elapsed time: 00:00:00.02]
['tctgaaatg', 'ctccacaaa', 'CTCACCCGC', 'agaatcagg', 'ttatgcctg', 'CATCTGATG', 'CCACCCCAT', 'ATTTCCAGA', 'cagagagag', 'CGTCACGAA']
10 random kmers from KI270855.1 [Elapsed time: 00:00:00.08]
['agccacctt', 'TTTGGAATG', 'GAACTGCCA', 'CCCTGCTCC', 'TTTCGCAGA', 'GATGTGAGC', 'GCCTGCTGC', 'ggaggcaga', 'CAAAGCCCC', 'aggtcCAGT']
10 random kmers from KI270853.1 [Elapsed time: 00:00:00.98]
['ggcgtgagc', 'aggcagaca', 'TTCTTCAGG', 'GTCCCCACA', 'tgagctgag', 'actctttaa', 'GAGACCCTA', 'Ggttatttc', 'ACTAGAGGA', 'caaaaataa']
10 random kmers from GL383556.1 [Elapsed time: 00:00:00.13]
['gGTACTTGG', 'aggtaatcc', 'gtgtgtgtg', 'TGTGCTATT', 'AAAACTACT', 'tagtaaTAA', 'TAgccagga', 'CCTGGCTGG', 'tagttattt', 'AAGCATCTA']
10 random kmers from GL383557.1 [Elapsed time: 00:00:00.03]
['GAGACCAAG', 'GGGAAGGAA', 'GCCAGGCCA', 'cactgcagc', 'caagaagag', 'AATTAtagc', 'ctcactatg', 'tgcctggtt', 'ttaagggat', 'gtgagctga']
10 random kmers from GL383563.3 [Elapsed time: 00:00:00.13]
['ctgctggga', 'TTAGGGAGA', 'CAGCCACAA', 'GAGGGGAGT', 'GCAGCAAAG', 'aatgcCCTA', 'GGAGCGCTC', 'cccaaattc', 'TGGGGTGAC', 'GCGAATGAG']
10 random kmers from KI270862.1 [Elapsed time: 00:00:00.15]
['AGAGGCACT', 'TCCTTGGTC', 'CCAAATTTg', 'GTCAGGAGC', 'TATTTTCCT', 'CATCTGGGG', 'GGATTTTAT', 'ttcacctca', 'cgtgagcca', 'CTACCTATT']
10 random kmers from KI270861.1 [Elapsed time: 00:00:00.07]
['GGCTGGGCA', 'TCCTCCCCT', 'GCGCTCCTC', 'gtaatcccc', 'agtagccgg', 'caccatgcc', 'atacatttt', 'ccagcttgg', 'gaaagattc', 'CGTCCGGGG']
10 random kmers from KI270857.1 [Elapsed time: 00:00:01.05]
['attttgtat', 'tcatatcaT', 'CTTATAACG', 'CCATGGAAG', 'gtcttgctc', 'catttaaca', 'atttatata', 'ACAGATGAA', 'tgttgaatt', 'TAGTATGAC']
10 random kmers from JH159146.1 [Elapsed time: 00:00:00.16]
['CCACATCAA', 'TCAAATATG', 'GTAATTCCA', 'caggtgttg', 'AATGTAGTG', 'ttcttagca', 'cttgttata', 'aacaaattt', 'ACTTGCGCT', 'atatatagt']
10 random kmers from JH159147.1 [Elapsed time: 00:00:00.03]
['CTATTCCAG', 'GGTGGTGGT', 'CTGATATAT', 'tattgattt', 'AGCATTTCC', 'AGCACCAGC', 'ttgattctt', 'GGAGCCAGG', 'TGGATGTTC', 'CAGGAATCA']
10 random kmers from GL383564.2 [Elapsed time: 00:00:00.04]
['ctgccacTG', 'TGGCTCCTG', 'ctgaggcag', 'tttacttta', 'gtgtatgtt', 'GTGGGCTGC', 'CAAATTGGC', 'GCCTTGGTA', 'attgtgcta', 'ATTGAGAAA']
10 random kmers from GL000258.2 [Elapsed time: 00:00:00.66]
['AGAGGAGTG', 'TAATTTCTC', 'accccagcc', 'AGAACCTGC', 'GGGGGAAAG', 'tgaccttat', 'ATTCTTAAG', 'ctccctccc', 'ttttcccaa', 'TCTACTGCC']
10 random kmers from GL383565.1 [Elapsed time: 00:00:00.12]
['CTTCTAGGc', 'aacagcttt', 'gcagggtat', 'tttgcattt', 'ttttttatt', 'TTACCAAAG', 'CCTGCCCTT', 'atttgtttt', 'CACTCTCAG', 'AATCATTTT']
10 random kmers from KI270858.1 [Elapsed time: 00:00:00.08]
['AATCAAAAT', 'AGAAAATTC', 'TTGACTGTC', 'cctcccacc', 'cccaagtag', 'AATCTAAAA', 'CACTATAAT', 'TTATTTGTC', 'AATAATATA', 'ACCAGCTTG']
10 random kmers from KI270859.1 [Elapsed time: 00:00:00.04]
['ATGTGGGTG', 'GGATTTGTG', 'aacattaga', 'gcccacctc', 'GAACCAATA', 'ACACAGACA', 'gagactcca', 'CACCAGTGG', 'aaaagtccT', 'CCTCCAAAG']
10 random kmers from GL383566.1 [Elapsed time: 00:00:00.03]
['TTCAACAGA', 'ctcggctca', 'ATTATTTGA', 'cgaggagga', 'TGTagtcgc', 'catatgagc', 'TGCCTGTGG', 'GTTCCAGCC', 'GAGCTGTGC', 'aactcaagt']
10 random kmers from KI270860.1 [Elapsed time: 00:00:00.06]
['TTGTCACTA', 'GCACCTGTT', 'CCTCCTGTG', 'gagatcgag', 'TCATTCATT', 'CCGCGTGCC', 'TAAGATAGC', 'gcctgcctc', 'TCCCACAGA', 'CCACAGACC']
10 random kmers from KI270864.1 [Elapsed time: 00:00:00.04]
['TGGTTCTTC', 'aatactagg', 'CAAGGAGGG', 'TTCACTTGT', 'TACTCTTAA', 'GCGATACAA', 'CTCACGGAT', 'ataacaatt', 'tcaattaat', 'tggtcttga']
10 random kmers from GL383567.1 [Elapsed time: 00:00:00.10]
['acatttttc', 'tcctatctc', 'caaaacagc', 'GCACTGGGA', 'agcTAGCAG', 'gatgagtat', 'AATCTTTGC', 'aagcagaga', 'CAGTGGTGG', 'GTTTAGACA']
10 random kmers from GL383570.1 [Elapsed time: 00:00:00.06]
['TAGGAGCTT', 'GTGGGACAG', 'atgtagttg', 'AAATGACCC', 'ATTTagttt', 'AAGTTAGAT', 'CTTTTTCTC', 'TCTCTGGTA', 'tcatgtcga', 'tacccagtc']
10 random kmers from GL383571.1 [Elapsed time: 00:00:00.07]
['AATTAGTAA', 'GTAATTCTA', 'ttgacaaat', 'TTGCAAGCT', 'ttcctttct', 'NNNNNNNNN', 'CAGTTGACT', 'NNNNNNNNN', 'GTGTGGGCA', 'catatttct']
10 random kmers from GL383568.1 [Elapsed time: 00:00:00.04]
['gcacaatat', 'cccttcctt', 'ccaatgcct', 'ttattgcat', 'AAGGCCGTG', 'CAATGATCC', 'ttttaaata', 'atattttta', 'GATCAGCCT', 'ATCATCAGT']
10 random kmers from GL383569.1 [Elapsed time: 00:00:00.06]
['CACCTGGCC', 'AGGCCACAT', 'GAAGACCAA', 'TCGACCATC', 'GAACTCAGG', 'atactGGTT', 'TTTTGTTAG', 'CTTCTCAGC', 'TGGCAGTCA', 'GAAGCTCAG']
10 random kmers from GL383572.1 [Elapsed time: 00:00:00.06]
['CCTGGGCCA', 'AACGGTTAT', 'AGGATTTAT', 'ACTGGTTCA', 'ccatgactg', 'CAAGTTCCC', 'attttaaaa', 'TCAGAAAAA', 'GGAAATGAA', 'GAGCGCGTT']
10 random kmers from KI270863.1 [Elapsed time: 00:00:00.06]
['TGTGAAATC', 'gggagggag', 'atgatggtg', 'TGGGGCCCC', 'ATTGTAGGA', 'GTGAAAGCC', 'CACCTGTGG', 'CAGACATTT', 'GACAGGCTA', 'GGATGGTCA']
10 random kmers from KI270868.1 [Elapsed time: 00:00:00.02]
['tttttgtag', 'GCTTGGAGA', 'CGTTGGCGG', 'CCCAGGGCA', 'AGGTCACAC', 'aggcgcccg', 'TCTGCTCCT', 'TTCCGTCAC', 'AGGACACGC', 'AAAAACAGC']
10 random kmers from KI270865.1 [Elapsed time: 00:00:00.02]
['agtgctggg', 'CTGCCTTCT', 'TGGCAGGGA', 'GTCCTCCAC', 'TCAACCCTC', 'CCTCCCAGT', 'caacggGAC', 'TCTCCCGCC', 'GGTAGGGTg', 'CGCCCGCTG']
10 random kmers from GL383573.1 [Elapsed time: 00:00:00.13]
['cccagcact', 'TCTGAAACC', 'AGATGTATT', 'ccccttttc', 'GCTGTCACT', 'tggtgatgg', 'gaaacactg', 'CACAaaggc', 'TTCAGGCCT', 'acatgtgcc']
10 random kmers from GL383575.2 [Elapsed time: 00:00:00.06]
['aaatgcaaa', 'gtctcactc', 'AAAAGAAGT', 'AATTTTCTA', 'TCTGGTGGT', 'ggttttctg', 'ACCAAAGCA', 'aacatgtta', 'TGGTACTTT', 'GAAACAGAC']
10 random kmers from GL383576.1 [Elapsed time: 00:00:00.07]
['GAaactgtg', 'ataaataaa', 'acgccactg', 'agctgcggt', 'ctgagcagc', 'tgtttatat', 'gaggtcagg', 'GTAGAgttt', 'TTCCAGTTA', 'ATTGCTGAC']
10 random kmers from GL383574.1 [Elapsed time: 00:00:00.05]
['GGTCCATTA', 'CCTTCAGTT', 'tggagtgca', 'TTAGTGAAT', 'TAGTTGGGC', 'cttgaaggg', 'CTCTGCCCA', 'TGAGCTAGC', 'gaatcgctt', 'ctgcactcc']
10 random kmers from KI270866.1 [Elapsed time: 00:00:00.02]
['ctgcaacct', 'aaaattagc', 'ttttttttt', 'ACATTGGCA', 'aatcccagc', 'GAcatttcc', 'caggagttt', 'cttgggagg', 'CTTCTAGTG', 'GTacttctg']
10 random kmers from KI270867.1 [Elapsed time: 00:00:00.08]
['AGGCTGAGT', 'AATTTGCAC', 'TGTTCCCTA', 'ATGCCCCTA', 'ACAGCAGCT', 'tctattgat', 'TATCAGGGT', 'cagacactt', 'gggaCCCAC', 'GCCATAGCC']
10 random kmers from GL949746.1 [Elapsed time: 00:00:00.36]
['taaatacac', 'CCCCAAGGG', 'NNNNNNNNN', 'CAGTGATCA', 'TTAAAGTAG', 'NNNNNNNNN', 'cttgccccc', 'TGGCTGGAA', 'NNNNNNNNN', 'TGAGGGTTG']
10 random kmers from GL383577.2 [Elapsed time: 00:00:00.07]
['GAATTGATG', 'GAGAAGACA', 'GCACATGTG', 'GACTGGAGT', 'aaaagagag', 'tttgagaca', 'GTTCAGAAG', 'CTTGGCTCT', 'GCATCCCTG', 'cgcaccatt']
10 random kmers from KI270869.1 [Elapsed time: 00:00:00.04]
['ACAGCTGGC', 'gtataattt', 'TTGTAACAC', 'CAGGCCTAG', 'CAGCATGGC', 'TCTGTCCCA', 'ATGACACCG', 'atcccagca', 'CTGGACCCC', 'TCTAACCTA']
10 random kmers from KI270871.1 [Elapsed time: 00:00:00.02]
['ttttttttt', 'ggtgggggg', 'CAGCGTCCT', 'aggcagcag', 'CTCCTGACC', 'aaagaaaat', 'ACCTCCCTC', 'cagctactc', 'GAAGGAGCC', 'CCCATGAGG']
10 random kmers from KI270870.1 [Elapsed time: 00:00:00.06]
['GCGGCCACT', 'ACTAACCTT', 'taaaacaaa', 'GCCTGAGAC', 'TAGATGAGT', 'TCCTGACTG', 'AGTTGtgtc', 'ACTTCTTTA', 'GGGGGGGAT', 'TTTTCAAGC']
10 random kmers from GL383578.2 [Elapsed time: 00:00:00.02]
['TTTGCTAAT', 'TGATAtcac', 'AGTATTGct', 'CAAATCTTT', 'agttttctt', 'tttctctgt', 'TGACACGCT', 'ttgtgtaca', 'atcccatgt', 'aggcaaTAA']
10 random kmers from KI270874.1 [Elapsed time: 00:00:00.06]
['aaccccagc', 'cagcggatc', 'attccaaac', 'aaccaactg', 'CTTTGGACA', 'ATCACATCT', 'CGTCAGACT', 'atgaaacaC', 'AACTGGAGC', 'aaaaattta']
10 random kmers from KI270873.1 [Elapsed time: 00:00:00.05]
['cttCTAGGA', 'GAGAATGAA', 'Tctttatag', 'tgctaaata', 'AGGAAACCT', 'AAGATCCCA', 'agataggaa', 'TTTGCTGCG', 'TTTTTTCTC', 'ttttttttt']
10 random kmers from GL383579.2 [Elapsed time: 00:00:00.07]
['tgaagccaA', 'GATTTCACA', 'ATTGCAGCA', 'catcaagga', 'GCCACTTAT', 'TCTTACTAG', 'tagagacgg', 'accatgccc', 'cttttaaaa', 'CTCATAGAA']
10 random kmers from GL383580.2 [Elapsed time: 00:00:00.03]
['GATGTGCCT', 'GTCAGCATC', 'GTGTATGGC', 'ttcccttcc', 'acatttggg', 'ACTTAAGTG', 'CTGTATTTG', 'ccctttctc', 'tgtatatgt', 'ACATGCTTT']
10 random kmers from GL383581.2 [Elapsed time: 00:00:00.04]
['cccagcagc', 'aacacagtg', 'gctggagtg', 'TTTAAACTT', 'ggattccag', 'GAAACTGTA', 'GGAGCATCT', 'cgtgtgcca', 'CTGTTGTAT', 'cagttttct']
10 random kmers from KI270872.1 [Elapsed time: 00:00:00.03]
['CATGAAGAG', 'GTTAAAGCT', 'CCCAAAGGG', 'GGTCCAGGA', 'gatTCCACG', 'CACGTGTGA', 'ggtttcgcc', 'AACAGACAC', 'CTGTGACGT', 'gggaTGGGG']
10 random kmers from KI270875.1 [Elapsed time: 00:00:00.09]
['TCACCTTGG', 'TGTTTTCCC', 'TCCAGTGTT', 'GTCCACGGG', 'TTTCGGACC', 'GCAGTGTCT', 'TCAATTTCC', 'tttctcatg', 'TAAATGATT', 'TGGCACCAC']
10 random kmers from KI270878.1 [Elapsed time: 00:00:00.07]
['GCCATGGCG', 'AGCACATTG', 'CTCAGCCGG', 'tttaaattc', 'CAGTGAGGC', 'AGACAGCCC', 'tctccctcc', 'CCAGCTAGG', 'CCTGCATCA', 'CAGGACAAC']
10 random kmers from KI270879.1 [Elapsed time: 00:00:00.10]
['ggaagctga', 'CCAGGGCTT', 'tgagccctg', 'GTGGGGCCT', 'TCATGGGGA', 'ACCAGGCCC', 'tactcagga', 'tgataaaat', 'aactcccca', 'ctgAGCAGG']
10 random kmers from KI270876.1 [Elapsed time: 00:00:00.09]
['gaggtcagg', 'GCAGTGAAG', 'ACACTTGAA', 'TCGGAGCAC', 'attaatatt', 'atcccagat', 'TTGGAGACC', 'ATATCCTTC', 'CTATATTCG', 'TGTCATCTT']
10 random kmers from KI270877.1 [Elapsed time: 00:00:00.04]
['TCACTGCCC', 'GCAGGACCT', 'CAGTTATTT', 'CATTGGAGG', 'tggccattt', 'AGGTTTGAA', 'cCCGCTCCC', 'GCAGCTTTC', 'CGCCCGCTC', 'CTGCCTTAG']
10 random kmers from GL383583.2 [Elapsed time: 00:00:00.03]
['AGTCAACCC', 'aaataagcc', 'tctcttccc', 'ggagaggtt', 'AAAAAAGAA', 'GTTCTCACC', 'gtctcaCAC', 'cctttcttc', 'CAATCTGAC', 'atcacttga']
10 random kmers from GL383582.2 [Elapsed time: 00:00:00.06]
['TTCTGTTAC', 'GTCATCATG', 'ttcaagtga', 'GTAGTTGAC', 'gatggtctc', 'ttaattcag', 'AATCAAAAG', 'AAAAACAAA', 'TCTTTGCTC', 'tacactaca']
10 random kmers from KI270880.1 [Elapsed time: 00:00:00.10]
['TGTTTCTGA', 'aacaggtgc', 'ttagtagag', 'Gactctatc', 'TCGGCAGGG', 'CCTGACGGA', 'GGCGTGGCC', 'GTTGACACT', 'TGTGGGGCC', 'GTTTCAATG']
10 random kmers from KI270881.1 [Elapsed time: 00:00:00.05]
['atatcaaat', 'TTTAAATCT', 'ttaatcatt', 'tgcccatga', 'attttaaaa', 'ccagtgata', 'aTAAACCTG', 'cAATGATGG', 'CTGACTATA', 'gggcATACC']
10 random kmers from KI270892.1 [Elapsed time: 00:00:00.06]
['gacacccta', 'CACTTTCTC', 'AGTACACAT', 'cctcacata', 'TCGTAGTTC', 'tggtgttta', 'AGAGGGGGG', 'GGTCCCTGA', 'gatgaCACA', 'ATAGGACCG']
10 random kmers from KI270894.1 [Elapsed time: 00:00:00.07]
['CCTGGGGCA', 'ACCtgcctc', 'caacatatg', 'TAGCGGAGC', 'AGACAGACC', 'gcaataagA', 'AGTGGGTCT', 'ATGATTTAG', 'CACTGTCCC', 'agccagcca']
10 random kmers from KI270893.1 [Elapsed time: 00:00:00.06]
['GAAAGGAGT', 'CACTCAAAA', 'GCTCGTGGC', 'AGCTGTCTC', 'GAACAGAGC', 'CTGTGGAGA', 'AGCAATGAA', 'TGCACACgg', 'TTAGGAAAC', 'TCACACTCA']
10 random kmers from KI270895.1 [Elapsed time: 00:00:00.06]
['TCCTGGCCA', 'TACACAGAA', 'CCACGCCTC', 'ggcagggag', 'CACTAAATC', 'GTCTCCATA', 'CAGGGAGGA', 'TTTCAACAT', 'tgtttttta', 'ccgacactt']
10 random kmers from KI270896.1 [Elapsed time: 00:00:00.13]
['cctggttag', 'GTCCAGGAG', 'accaggccc', 'taattgttc', 'GGGACACTC', 'CATTGGCTC', 'TAATaaacg', 'GCCATTTCT', 'ccactgggt', 'gaaaaagag']
10 random kmers from KI270897.1 [Elapsed time: 00:00:00.42]
['TAGGTTCTG', 'caaagtgTG', 'CCATTCTTA', 'GCCAAACCA', 'ttttttttg', 'ATCAGATTG', 'cgcccaggc', 'tgtttgtgg', 'caATATCAT', 'gtaactaac']
10 random kmers from KI270898.1 [Elapsed time: 00:00:00.07]
['CTGCGCATT', 'CCCACGACG', 'caaaggcac', 'gtgtgtgtg', 'ttcttctta', 'tccagatTC', 'AATCAAATG', 'TGTAATAAA', 'tttccaaat', 'TTGATCTTG']
10 random kmers from GL000251.2 [Elapsed time: 00:00:01.79]
['CAATTAgct', 'cccagtggc', 'TGAGGGTCA', 'ctcccctct', 'tGTTATCTA', 'CTTGTATTG', 'ggctcactg', 'atttctatt', 'AGAGTGAGT', 'GGAAAAGGA']
10 random kmers from KI270899.1 [Elapsed time: 00:00:00.19]
['TACAGAGGC', 'AGCCCCCTG', 'CCGTGGTGG', 'AGCAATAAA', 'CGGGAGACG', 'GAAATTATA', 'TAAGACAGA', 'GGGTGTGTC', 'ATCTAAACA', 'AGAGAATAC']
10 random kmers from KI270901.1 [Elapsed time: 00:00:00.05]
['AACGGAACA', 'gctcctgga', 'cagcttccc', 'ACTCCGGGG', 'CTCACTTCC', 'gcccccact', 'aagttttag', 'TAATGGGGA', 'TTGGATGCC', 'TAGTCCTCC']
10 random kmers from KI270900.1 [Elapsed time: 00:00:00.11]
['TTTTATTCG', 'GCCACATTG', 'TGGAATATG', 'tcttccaaa', 'CTCGATTTA', 'TCTCAACAG', 'CTGAGAAGA', 'ATAGTGGTT', 'CACCTGACC', 'GTCACCACC']
10 random kmers from KI270902.1 [Elapsed time: 00:00:00.04]
['tcactgcca', 'CTGCTGGAT', 'CTGCACCAA', 'CCCTTGTGG', 'GCCACAGGG', 'GGCACAACT', 'CTTAGAGAA', 'CCCGCACAC', 'GGTAGAAGT', 'GACACATGA']
10 random kmers from KI270903.1 [Elapsed time: 00:00:00.07]
['catctctac', 'CCCTAGGGT', 'GCGGAGGCC', 'TCCCCTGCC', 'AGAGCTGTG', 'cccctcatt', 'ATCAATCAA', 'CTCTGGCCA', 'CCACccgtc', 'AGCAAATTG']
10 random kmers from KI270904.1 [Elapsed time: 00:00:00.20]
['ATGTCTCAC', 'CTAGCAAAG', 'TATTTCTTC', 'TACagatat', 'AATGTAACT', 'gaattttca', 'atgtttgAT', 'CAACTGTAA', 'tcataagtg', 'CAGCCTCAG']
10 random kmers from KI270906.1 [Elapsed time: 00:00:00.08]
['caaaggctg', 'GGCAAGACA', 'AATAACAAG', 'ccgaggcag', 'TTTAATAAA', 'GTGGCATTT', 'AAACTTCAC', 'acctggcca', 'GTGACCTGG', 'CTGCTGGGA']
10 random kmers from KI270905.1 [Elapsed time: 00:00:01.93]
['agccaccac', 'NNNNNNNNN', 'CAAGTGTAA', 'TTACTGTTC', 'CCTTGTTTA', 'ctgtttcag', 'atgcccttt', 'acagtcatg', 'AGACCTAAa', 'TTGAGGGAG']
10 random kmers from KI270907.1 [Elapsed time: 00:00:00.18]
['GGTCATTTG', 'CATGTGGGA', 'TAGATGGGG', 'GTTGTATTC', 'ACAGACTTG', 'GCAGAGACC', 'GATGTCAGA', 'tgtgcctgg', 'CTGCTTCCT', 'cagCCCGAG']
10 random kmers from KI270910.1 [Elapsed time: 00:00:00.05]
['CGCTTCTCA', 'TTTCTTTCC', 'CTGAGAGGC', 'tccagcctg', 'CCCACCTGC', 'gcctgtaat', 'TCTCGGCTC', 'ATTTCCAGG', 'ctctgtcaa', 'cctgaccag']
10 random kmers from KI270909.1 [Elapsed time: 00:00:00.11]
['AACTTGTCA', 'GAGGATAAC', 'CAATGGATA', 'GCCCTCTGA', 'CCTTCTAAG', 'AATGGGATA', 'aaatacaaa', 'aatctgtat', 'tggaaaatg', 'CCCCTTGTG']
10 random kmers from JH159148.1 [Elapsed time: 00:00:00.03]
['TGTAAATAC', 'ttggcatgt', 'AAGTTTTGA', 'gccctTCTC', 'tttcaccat', 'GGAAGCCAT', 'TGAACCTTC', 'CCACAGCTG', 'GTGTGCTGC', 'CTGCTGCAG']
10 random kmers from KI270908.1 [Elapsed time: 00:00:00.51]
['CTCAGCACA', 'TGTCTGCTG', 'CAAGCCCTA', 'atacatatc', 'AGGAATCTC', 'GAGAAGCAA', 'ggctggagt', 'tggcgggct', 'tgaggtcag', 'CTTGAATTT']
10 random kmers from KI270912.1 [Elapsed time: 00:00:00.09]
['CTGGGGCCA', 'ACTGTTTAC', 'TTGAAGTGT', 'GTCTGTCCT', 'TGTCGACCA', 'AAATTCTAA', 'GTAATTACA', 'aaataaata', 'GTCTTTTGA', 'CACAACCCG']
10 random kmers from KI270911.1 [Elapsed time: 00:00:00.05]
['catcctata', 'AATAAGCTA', 'CCATGACCG', 'TGGTACTGC', 'AGGCCTTCC', 'ACATTCCTA', 'CACAAATAA', 'tggctgatg', 'ACACTCCAT', 'TCTGGTCAC']
10 random kmers from GL949747.2 [Elapsed time: 00:00:00.25]
['ccagtgatg', 'CCTTCTCTC', 'CACAGGCGG', 'ttgggggta', 'GTCAGCGCC', 'gctgggact', 'ATTCAACTG', 'CCTTTATCT', 'CAAGTAGTT', 'ctggagtgc']
10 random kmers from KB663609.1 [Elapsed time: 00:00:00.04]
['GACGGACCG', 'TGGAAGGGG', 'CCaaacctg', 'ACCTCTCCC', 'GTTTCCCTG', 'TCCCAGACA', 'ctctcagct', 'CCCTAGTTG', 'CATAATGAA', 'cagtctggg']
10 random kmers from KI270913.1 [Elapsed time: 00:00:00.09]
['agcctgggt', 'CACTGAAAT', 'aagggtggg', 'aagcaaaat', 'TGCATTCCT', 'GAGGATGAA', 'TCAAGTTTC', 'CAAGCgcca', 'GGAGTGATG', 'ttttgcact']
10 random kmers from KI270924.1 [Elapsed time: 00:00:00.06]
['TACTGAGCA', 'CTATAACTC', 'CAATAACAA', 'CACCGACGC', 'tgctttgtt', 'ACTGCCTTA', 'GCAGGAGGA', 'AGGGGGTGG', 'TCTAGCAAA', 'ATAATGATG']
10 random kmers from KI270925.1 [Elapsed time: 00:00:00.19]
['TGTGTAGCT', 'AGACTTTAG', 'CATTATAAT', 'CTCAGAGCT', 'AGCTGGCTC', 'CCCCAGGGA', 'CCAGGTAGA', 'ccctccaaa', 'taaaatcaa', 'ATATGgagc']
10 random kmers from GL000252.2 [Elapsed time: 00:00:01.76]
['NNNNNNNNN', 'AGGCAAGCA', 'ctttcctcc', 'tgatatgtg', 'GAAGTGGCC', 'TTATGGTCC', 'GTACCCCAG', 'CCTACGAAA', 'ATGCTCTGA', 'NNNNNNNNN']
10 random kmers from KI270926.1 [Elapsed time: 00:00:00.20]
['atgtatCTG', 'ggccaatgt', 'CGACTTACT', 'GACAACATC', 'GATAATTTG', 'tttagagaa', 'GATTTTGTG', 'ACAAACCTG', 'ATGGTGGTG', 'GAAAAGCAg']
10 random kmers from KI270927.1 [Elapsed time: 00:00:00.08]
['ACCTGTGTC', 'CCTTGTGCC', 'TCCCCGCAT', 'GGCTGCCTG', 'CTTTTCCAT', 'ACATgggta', 'GGTTCGTGC', 'CTGAGGGGC', 'CACCGCATG', 'AAGGAACTG']
10 random kmers from GL949748.2 [Elapsed time: 00:00:00.38]
['NNNNNNNNN', 'TCGGCGGGG', 'NNNNNNNNN', 'cctgcacTT', 'NNNNNNNNN', 'aattggtga', 'NNNNNNNNN', 'cgcagtgtt', 'TGCTTAGCT', 'cacaatttt']
10 random kmers from KI270928.1 [Elapsed time: 00:00:00.08]
['GAATTATGA', 'tggggaggg', 'ACAGAAGCC', 'ttgcagtga', 'ccaccatgc', 'CCTGATGTG', 'TGCTGCGTA', 'tgtggtccc', 'GGATGGAAG', 'ggccgagac']
10 random kmers from KI270934.1 [Elapsed time: 00:00:00.06]
['AGTGTCAAT', 'taaaCCATA', 'CCAAACGGG', 'gttcacaca', 'ACCATTGGC', 'tttacttcc', 'GAAATGCCT', 'atacaaaaa', 'gagacgagt', 'tttggtttt']
10 random kmers from GL000253.2 [Elapsed time: 00:00:01.73]
['ggcggtgca', 'tgactagct', 'CTCAGACAG', 'CAAAGAAGA', 'TGGCTGCAT', 'TCCATTTCA', 'agcccagag', 'TCCAGTTCT', 'aaaattctc', 'GGCATTTCT']
10 random kmers from GL949749.2 [Elapsed time: 00:00:00.51]
['NNNNNNNNN', 'CTTTGGAGA', 'aaaagtaag', 'cctcccggg', 'NNNNNNNNN', 'cccagctac', 'tataaatac', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN']
10 random kmers from KI270935.1 [Elapsed time: 00:00:00.09]
['TGCTCCAAG', 'TCTCGGAGC', 'CTAACTCAA', 'AAAGGAGGC', 'CGTAACAGT', 'ATGGGTTTG', 'agttactta', 'CCCCAGCTG', 'TGCTcggca', 'gaggaaggg']
10 random kmers from GL000254.2 [Elapsed time: 00:00:01.80]
['NNNNNNNNN', 'NNNNNNNNN', 'CTGACTGCA', 'gtcttccca', 'tcaaaatat', 'CTATATGGG', 'NNNNNNNNN', 'GACCATGTT', 'TTTTGTAAA', 'tccgcctcc']
10 random kmers from GL949750.2 [Elapsed time: 00:00:00.51]
['NNNNNNNNN', 'gccaccatg', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'tgtatgaaa', 'acaaaaaat', 'NNNNNNNNN', 'AGGGGCTTC', 'NNNNNNNNN']
10 random kmers from KI270936.1 [Elapsed time: 00:00:00.08]
['tcacaccta', 'gcacAATCA', 'AAGGCCGTC', 'agcctgacg', 'CTCCCTTCC', 'AAAAACAAC', 'gatggggtt', 'AGCAAACTA', 'aaaaaaaaa', 'cccaggctg']
10 random kmers from GL000255.2 [Elapsed time: 00:00:01.72]
['AGCGCCCAG', 'AGGTATCCA', 'CTACTAATG', 'tacaggcat', 'AGGATTCAG', 'gctggtctt', 'aaaatagct', 'GCTGCCAGC', 'TACCTTCAG', 'ggctgagtc']
10 random kmers from GL949751.2 [Elapsed time: 00:00:00.48]
['TTATGCTTC', 'NNNNNNNNN', 'CCCTCAGGT', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'NNNNNNNNN', 'atatataca', 'NNNNNNNNN']
10 random kmers from KI270937.1 [Elapsed time: 00:00:00.08]
['ATGAACAAA', 'TGCTACATA', 'GACATTGAC', 'ccttaTTAC', 'CATCCTCCC', 'aatctagaa', 'GGGATGGGG', 'tggtgatgg', 'GCAAACTGT', 'GTATCCACA']
10 random kmers from GL000256.2 [Elapsed time: 00:00:01.83]
['acatgtcac', 'TGAGGAAGT', 'NNNNNNNNN', 'NNNNNNNNN', 'tttatttcc', 'TGGgttcta', 'TTCCTGTCT', 'GTTTTGTTA', 'NNNNNNNNN', 'ctaggaatc']
10 random kmers from GL949752.1 [Elapsed time: 00:00:00.49]
['TGTTAACAG', 'tggCATGAG', 'CTGGTCTCT', 'GCAATGGAG', 'gcAGAGAAG', 'AGGGGAACA', 'GGCACTGGA', 'GTCCTGTCG', 'aagtaatac', 'CTGAGCAGG']
10 random kmers from KI270758.1 [Elapsed time: 00:00:00.05]
['GTTAGGCTT', 'GGGATTTTG', 'CACACTCCT', 'GGCGAATGC', 'TGGAAATCT', 'TCTTTGTCT', 'AATATTCCT', 'tctttcctc', 'AAAGAGTCT', 'TGTGATATG']
10 random kmers from GL949753.2 [Elapsed time: 00:00:00.27]
['NNNNNNNNN', 'ATTCTTACA', 'attacagct', 'NNNNNNNNN', 'GCCTCCATC', 'GGAGGGTCT', 'GTCTGAGGA', 'TTCTGTGGA', 'CTATtagga', 'ACCCAGAGG']
10 random kmers from KI270938.1 [Elapsed time: 00:00:00.41]
['TTGCATATC', 'TCCTCACCC', 'gcagaggtt', 'caccatgtt', 'GGTCCTGGG', 'TCAATAGGT', 'CACCCACAG', 'GAGAAGGGA', 'gcctcagcc', 'aagatcatg']
10 random kmers from KI270882.1 [Elapsed time: 00:00:00.11]
['ATTCATGAT', 'tctccaacc', 'ACACACAGT', 'ACTCTTTGG', 'ctcagctaa', 'GAGTCAGTG', 'ctataacCT', 'ttttgcttt', 'TTGTCACTC', 'CCCAGAGGA']
10 random kmers from KI270883.1 [Elapsed time: 00:00:00.06]
['GAATGAAGA', 'GGGGCTACA', 'gtgtgtgca', 'tcatgccac', 'GAGTCCCAG', 'ATTTCTTGA', 'AACACTCCT', 'CGATGCCTG', 'Acgtcctgt', 'GGTGTCtta']
10 random kmers from KI270884.1 [Elapsed time: 00:00:00.05]
['GCTAGTTAG', 'CCGCACTGC', 'CCCCAAATA', 'agccaggca', 'CACCATCTC', 'CCACCTTAT', 'TTCACCAGG', 'aagatgtGG', 'gaaacatcc', 'TTACTCTCC']
10 random kmers from KI270885.1 [Elapsed time: 00:00:00.06]
['TGGAGAAAA', 'GCCTCCCTT', 'acacacaca', 'GGCCCTGGG', 'atgttggct', 'tccactcca', 'acccaggag', 'TCACCTGTG', 'tatctatca', 'TTTAGGgct']
10 random kmers from KI270886.1 [Elapsed time: 00:00:00.07]
['CTCCTGCTT', 'atatataaa', 'TGAAGTCCC', 'acatgcgcc', 'GGTGGGGGC', 'ctgacttct', 'atggtgaaa', 'ATAATgtta', 'CTTCCCCTA', 'CATTGATTT']
10 random kmers from KI270887.1 [Elapsed time: 00:00:00.07]
['TGtgaatat', 'aaaaaaaaa', 'tggacaagg', 'attttgagg', 'gaatttctt', 'ACAAAACCC', 'GAGTGATAG', 'cttcacaga', 'ataccaaaa', 'TTCCATGTT']
10 random kmers from KI270888.1 [Elapsed time: 00:00:00.05]
['CTACTGCAG', 'GTGTGGAGA', 'TGTACAAGA', 'TCCATGACA', 'ATCATGGAG', 'AGTAGGAAA', 'CATCTCTCT', 'TGACCCAAG', 'Tcctggaga', 'aatttataa']
10 random kmers from KI270889.1 [Elapsed time: 00:00:00.06]
['AAAGGTGGA', 'tcctgggtt', 'gtactaaaa', 'cccattcag', 'ATGACACCT', 'TTTGTGATC', 'ATCTGCAGG', 'ACTTGTCCT', 'TCAGTTGTA', 'ctggtatta']
10 random kmers from KI270890.1 [Elapsed time: 00:00:00.06]
['acacccggc', 'CATCGACAG', 'cctccctgt', 'TCATCTCTT', 'TTTAACACT', 'GTGTTGTAT', 'CCCCTGCTC', 'AGGAAAATC', 'CACTATTTG', 'ctttcttcc']
10 random kmers from KI270891.1 [Elapsed time: 00:00:00.06]
['ctttttgtg', 'TGCTGGCAC', 'TCAGCAGGA', 'TTCATAgta', 'AATCAAAGC', 'ATTGTGGGC', 'TACCCTTCC', 'GGCACATAT', 'TCTTGAAAC', 'TGACTTTTC']
10 random kmers from KI270914.1 [Elapsed time: 00:00:00.07]
['TGCATATTT', 'acacagttt', 'AGGAGCTCT', 'tacttcttt', 'tgagatgga', 'TTATAGCTC', 'TAGGCAAGA', 'ggctaaaat', 'gagactctg', 'TTGCCATGC']
10 random kmers from KI270915.1 [Elapsed time: 00:00:00.06]
['cctccagag', 'attgccaag', 'GTGAGGCTG', 'TATCTCCAA', 'atatataaa', 'GGGCCCTGG', 'taaaattat', 'AGAGTCCCA', 'ACACCCTGT', 'TCACTCCAA']
10 random kmers from KI270916.1 [Elapsed time: 00:00:00.06]
['gcctgtaat', 'TTTCTATCT', 'gcacctgta', 'AGGAGGACC', 'ACATGTCAT', 'gcacggtgg', 'CAGCACCCA', 'ATGTAGGCT', 'CGATTTCAG', 'acgagaatc']
10 random kmers from KI270917.1 [Elapsed time: 00:00:00.07]
['AGAAAACCT', 'CGAGAGGCA', 'TTCTGATTG', 'caggtgatc', 'tgcctcagc', 'CAGATCGTG', 'CCATCTGGG', 'TATTTATTT', 'GCAGCCCAG', 'ttttgtgtg']
10 random kmers from KI270918.1 [Elapsed time: 00:00:00.04]
['tcaggattc', 'CTCTGATGA', 'CCCAATATT', 'aagaaatgt', 'TCTGAAAAC', 'Tatgggcct', 'tagcccagg', 'AAAGAAGGT', 'TAATGGGAC', 'ATCTAAATC']
10 random kmers from KI270919.1 [Elapsed time: 00:00:00.06]
['TCTTCCCAT', 'gctgtagaA', 'aaTGCTTTT', 'CGTTCCTAT', 'taAACAAGt', 'tttgttttt', 'GGATGTTAT', 'CTCTACTCT', 'ATACCACCT', 'GGCAAGTCC']
10 random kmers from KI270920.1 [Elapsed time: 00:00:00.07]
['CCAACCTCA', 'tcgcttgaa', 'AAAGCACTG', 'ATAGTCTTT', 'acatacaaa', 'taaattttg', 'TCACAGGTA', 'CGCACCATG', 'ACCCCCAAC', 'ATGTTTTGA']
10 random kmers from KI270921.1 [Elapsed time: 00:00:00.10]
['taggagtgg', 'gtttcccaa', 'TGCGGAGTA', 'acatggaga', 'gatgataaa', 'CGGGACATA', 'GAGGAAGGA', 'aaataaaat', 'gtggctcac', 'TAATAATAC']
10 random kmers from KI270922.1 [Elapsed time: 00:00:00.07]
['Aagttgtta', 'ATATGTAGA', 'ATCTAGAGG', 'TCAGAGACC', 'CGACACAAA', 'GACCTGGCA', 'tagatatag', 'ATGAGGGTG', 'cgcccggcc', 'TTTtgtttg']
10 random kmers from KI270923.1 [Elapsed time: 00:00:00.07]
['TGGTATTTG', 'CACTTTCTt', 'AGGGCAGTG', 'tgactaatt', 'tcaagctct', 'CAAGCTCTG', 'TAAACAGGA', 'GATAATTTG', 'CCATTTTGG', 'AGtgtcttt']
10 random kmers from KI270929.1 [Elapsed time: 00:00:00.06]
['tatggccct', 'GCAGTAAGG', 'gtgagccac', 'ATCTTAACA', 'GAGGGGAAG', 'gagaaagag', 'GTTgtctcc', 'aagtccttg', 'AAATTCTAA', 'TTCTTTTCT']
10 random kmers from KI270930.1 [Elapsed time: 00:00:00.07]
['CCTGGAGGA', 'GTCAGCTCC', 'ctgtgtctc', 'TGGACTGGG', 'catgttggc', 'atttcgtGA', 'ctgctaaaa', 'aaaatacaa', 'tctgtcacc', 'caccttctc']
10 random kmers from KI270931.1 [Elapsed time: 00:00:00.06]
['AGGAGGGTA', 'CTGAGTGAG', 'GTTGAGATG', 'ACGAGAGCG', 'ACACAAGGT', 'GTTGGTGTG', 'ggagaggtg', 'agaacggtG', 'CAGTGGAAA', 'TCCTCACAT']
10 random kmers from KI270932.1 [Elapsed time: 00:00:00.07]
['CAAGTAATC', 'ttttctcac', 'ATCACATGT', 'aatattttt', 'GAAAACGCA', 'TAGAACTGT', 'TGCGTTCAG', 'CCTCTCACC', 'tttggattG', 'ccctccacc']
10 random kmers from KI270933.1 [Elapsed time: 00:00:00.06]
['AGGTGGGAC', 'tagatttca', 'ACTGAGAAA', 'AGATGGAAA', 'acaaaaact', 'CTTTAGGAC', 'ggctgggca', 'cgtctgtca', 'CCCATTCCT', 'TCTCTCCTC']
10 random kmers from GL000209.2 [Elapsed time: 00:00:00.06]
['ATCACGAGA', 'gtgcagcac', 'CATAAAGTG', 'GTGTGGTAA', 'GTCAACAAA', 'GTAAGATAA', 'AAATCCTCT', 'cttgagagg', 'GACCCCTTC', 'ttgttattg']
10 random kmers from J01415.2 [Elapsed time: 00:00:00.01]
['TATTCATCC', 'CACTTTCCA', 'AAAAACTAT', 'AAACAAATA', 'TCCGCCAAC', 'TAAAATGAC', 'ACAATCCCC', 'GCTCTGAGC', 'TACGACCAA', 'ACCATACAC']
Total elapsed time: 00:22:03.37